## Register and buy item (for free lol) at https://api-production-8692.up.railway.app/

In [ ]:
# pip install snowflake-connector-python, psycopg2, --upgrade snowflake-sqlalchemy
# pip3 install ipykernel

In [ ]:
# importing libraries
import pandas as pd
from sqlalchemy import create_engine, inspect
import psycopg2

# from snowflake.sqlalchemy import URL
# from sqlalchemy import create_engine

:

In [2]:
# establishing the source engine
src_engine = create_engine('postgresql+psycopg2://postgres:QztLWcoQoMcFPKoKgCyuDwUPjOHUYdtO@trolley.proxy.rlwy.net:50067/railway')

In [3]:
# call the inspect function to get table names automatically

inspector = inspect(src_engine)

table_names = inspector.get_table_names()
print("printing the table_names: \n\t", table_names)

printing the table_names:
	 ['categories', 'products', 'customers', 'orders', 'coupons', 'order_items', 'payments', 'shipping', 'inventory', 'reviews']

In [ ]:
# # checking the tables accessed
# df1 = pd.read_sql(f"select * from categories", src_engine)
# df1.head()

### using a list method

In [ ]:
# dfs = []
# for tables in table_names:
#     df= pd.read_sql(f"select * from {tables}", src_engine)
#     dfs.append(df)

# customers_df = dfs[3]
# customers_df.count()
# customers_df.tail()

### using the dict method

### using listdict

In [ ]:
# for tables in table_names:
#     df= pd.read_sql(f"select * from {tables}", src_engine)
#     file_name = f"{tables}_df"
#     globals()[f"{file_name}"] = df
#     # dict_list[f"{file_name}"] = df

# print(dict_list.keys())

In [4]:
dict_list={}

In [5]:
for tables in table_names:
    df= pd.read_sql(f"select * from {tables}", src_engine)
    file_name = f"{tables}_df"
    dict_list[file_name] = df #store as key and vaariables
    globals()[file_name] = df  #store the dfs in the global space

print(dict_list.keys())

dict_keys(['categories_df', 'products_df', 'customers_df', 'orders_df', 'coupons_df', 'order_items_df', 'payments_df', 'shipping_df', 'inventory_df', 'reviews_df'])

In [ ]:
# dict_list

In [ ]:
# Example: saving a new dataframe thats transformed to replace the raw in the dictionary, that way can send the hwole dictionary directly to snowflake
# trans_orders_df = orders_df.head(2)
# dict_list['orders_df'] = trans_orders_df
# dict_list['orders_df']
# dict_list['categories_df'] = 'Hey my man'
# dict_list

In [ ]:
# def engine():
#     db_user = input("whats your db username?")
#     db_password = input("whats your db password?")
#     db_host = input("whats your db host?")
#     db_port = input("whats your db port?")
#     db_name = input("whats your db name?")
#     print("creating your source engine...")
#     src_engine = create_engine('postgresql+psycopg2://db_user:db_password@db_host:db_port/db_name')
#     return src_engine

# def extract(src_engine):
#     print("engine connection created?, analysing tables:")
#     inspector = inspect(src_engine)
#     table_names = inspector.get_table_names()
#     print("the tables present in your database are the following:", table_names)
#     dict_list={}
#     for tables in table_names:
#         df= pd.read_sql(f"select * from {tables}", src_engine)
#         file_name = f"{tables}_df"
#         dict_list[file_name] = df #store as key and vaariables
#         globals()[file_name] = df  #store the dfs in the global space
#         print("keys in this dict", dict_list.keys())
#         return dict_list

In [ ]:
# for name, df in dict_list.items():
#     file_name = f"{name}_df"
#     dict_list[file_name]= dict_list[name]
#     # print

### use sqlalchemy pandas

In [ ]:
# from snowflake.sqlalchemy import URL
# from sqlalchemy import create_engine

In [ ]:
# 'snowflake://<user_login_name>:<password>@<account_identifier>/<database_name>/<schema_name>?warehouse=<warehouse_name>&role=<role_name>'
# URL = 'snowflake://CHEEZY:Mathematics%40999@PPXZJRB-KR90803/USER$CHEEZY/KARTIFIED?warehouse=COMPUTE_WH&role=ACCOUNTADMIN'
# dest_engine = create_engine(URL)

In [ ]:
database = 'KARTDB'
raw_schema = 'KARTIFY'
trans_schema = 'KARTIFY_TRANS'
gold_schema = 'KARTIFY_GOLD'

url = URL(
    account = 'PPXZJRB-KR90803',
    user = 'CHEEZY',
    password = 'Mathematics@999',
    database = database,
    # schema = trans_schema,
    warehouse = 'COMPUTE_WH',
    role='ACCOUNTADMIN',
)

dest_sf_engine = create_engine(url)

In [ ]:
# to send yr dataframe
# df.to_sql('PHOENIX_CUSTOMERS', 
#                        dest_sf_engine, 
#                        # schema = specify_your_schema, 
#                        if_exists='fail', 
#                        index=False
#                       )

In [ ]:
try:
    for title, table in dict_list.items():
        table_df = table.to_sql(
            title, 
            dest_sf_engine,
            schema = 
            if_exists='fail', 
            index=False
        )
        print(f"{title} table has been uploaded")
except Exception as e:
    print("Error is ", e)
# dest_engine.close()

### Use snowflake connector pandas

In [ ]:
# Connect to snowflake

In [ ]:
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas

In [ ]:
db = 'KARTDB'
schema = 'KARTIFY'

In [ ]:
dest_conn = snowflake.connector.connect(
        account='PPXZJRB-KR90803',
        user='CHEEZY',
        password='Mathematics@999',
        warehouse='COMPUTE_WH',
        database= db,
        schema= schema
)

In [ ]:
# testing
# details = write_pandas(dest_conn, categories_df, "categories", auto_create_table = True)

In [ ]:
try:
    for name, df in dict_list.items():
        details=write_pandas(conn = dest_conn, df= df, table_name = name.upper(), auto_create_table = True, use_logical_type = True)
        print(f"successfully uploaded {name}: {details[0]}, number of rows: {details[2]} ")
except Exception as e:
    print(f"Error is {e}")
dest_conn.close()

In [ ]:
# # write multiple files to sf
# # why is this always failing, because of the databvase, sf doesnt allow reading tables there
# for table_name, df in dict_list.items():
#    details = write_pandas(dest_conn, df, table_name, auto_create_table = True, db='USER$CHEEZY', schema='KARTIFIED', use_logical_type=True)

In [ ]:
# #### for dropping tables, we made use of the cursor 

# # cursor = dest_conn.cursor()

# # # for name in dict_list.keys():
# #     try:
# #         cursor.execute(f"DROP TABLE IF EXISTS {name.upper()} ") # We use IF EXISTS so the code doesn't crash if a table is already gone
# #         print(f"successfully droppped: {name} ")
# #     except Exception as e:
# #         print(f"Error dropping: {e} ")

# # cursor.close()

# #### for dropping schema, we made use of the cursor 

# # cursor= dest_conn.cursor()
# # try: 
# #     cursor.execute(f"DROP TABLE CATEGORIES_COPY;")
#       cursor.execute(f"DROP TABLE CATEGORIES_OKIKI")
# # except Exception as e:
# #     print("Error is:", e)

# # cursor.close()
# # # dest_conn.close()

### Transformations

#### transform the customers table

In [ ]:
# dict_list.items()

In [ ]:
# customers_df.columns

In [ ]:
# things i plan to do
# 'id', 'first_name', 'last_name', 'email', 'city',
#        'state', 'country', 'created_at', 'updated_at'
# state = .title() strip() where != None(convert null values to N/A)
# city = .upper() strip
# created at > 2026-03-11

In [ ]:
# customers_df['state'].unique()

In [6]:
in_prog_customers = customers_df.copy()

In [ ]:
# get unique values to know what to change
# in_prog_customers['state'].unique()
# in_prog_customers['fullname']
# in_prog_customers['city']
# in_prog_customers['country'].unique()

In [7]:
in_prog_customers['state'] = in_prog_customers['state'].str.title().str.strip()
in_prog_customers['fullname'] = in_prog_customers['first_name'] + ' ' + in_prog_customers['last_name']
in_prog_customers['city'] = in_prog_customers['city'].str.upper()
in_prog_customers['country'] = in_prog_customers['country'].str.title().str.strip()

In [ ]:
in_prog_customers.head()

In [8]:
in_prog_customers.isna().sum()
none_columns = ['phone', 'address', 'city']
in_prog_customers[none_columns] = in_prog_customers[none_columns].fillna('N/A')
in_prog_customers.head()

,id,first_name,last_name,email,phone,address,city,state,country,postal_code,password,is_active,created_at,updated_at,fullname
0,1,Test,User,testuser@test.com,N/A,N/A,N/A,None,Nigeria,None,$2b$12$8LYwj2E2rHoTauQlCWOKh.l.riliw5AWEDhZ6et...,True,2026-03-11 02:39:43.500028+00:00,2026-03-11 02:39:43.500028+00:00,Test User
1,2,Ahmed,Oladapo,biyiguy@gmail.com,+2349091390809,230 borno way,LAGOS,Abia,Nigeria,234101,$2b$12$fi1k5SMmbZWQ5hwIKi/cs.u4wjr8cKtiHNxAzzE...,True,2026-03-11 02:40:19.433485+00:00,2026-03-11 02:40:19.433485+00:00,Ahmed Oladapo
2,53,Megan,Stephenson,donna55@example.com,001-292-983-4859,10808 Mary Mall Suite 271,IBADAN,None,Nigeria,None,$2b$12$tII5OYX1LCB7W/k7a6o3teAkMMGuGC59QHShF3....,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00,Megan Stephenson
3,54,Lauren,Flowers,judith52@example.net,(396)349-3118x207,9945 Pamela Field,KANO,None,Nigeria,None,$2b$12$UnXHrfcWhkPiTGn9yAzJ5eb19no19qluCIBRXb/...,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00,Lauren Flowers
4,55,Charles,Ramirez,proctorcharles@example.org,001-876-237-8316x690,951 Adam Mountains,LAGOS,None,Nigeria,None,$2b$12$srDCNrvh0yiFZskuAoKVz.3kLptk5M5YQzTRnqL...,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00,Charles Ramirez

In [9]:
in_prog_customers.loc[:, ['id', 'first_name', 'last_name', 'fullname', 'email', 'city', 'state', 'country', 'created_at', 'updated_at']]

,id,first_name,last_name,fullname,email,city,state,country,created_at,updated_at
0,1,Test,User,Test User,testuser@test.com,N/A,None,Nigeria,2026-03-11 02:39:43.500028+00:00,2026-03-11 02:39:43.500028+00:00
1,2,Ahmed,Oladapo,Ahmed Oladapo,biyiguy@gmail.com,LAGOS,Abia,Nigeria,2026-03-11 02:40:19.433485+00:00,2026-03-11 02:40:19.433485+00:00
2,53,Megan,Stephenson,Megan Stephenson,donna55@example.com,IBADAN,None,Nigeria,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
3,54,Lauren,Flowers,Lauren Flowers,judith52@example.net,KANO,None,Nigeria,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
4,55,Charles,Ramirez,Charles Ramirez,proctorcharles@example.org,LAGOS,None,Nigeria,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
...,...,...,...,...,...,...,...,...,...,...
123,174,Lola,Bakre,Lola Bakre,Lardivahapparels@gmail.com,LAGOS,Logos,Nigeria,2026-03-18 21:12:21.072851+00:00,2026-03-18 21:12:21.072851+00:00
124,175,Judy,P,Judy P,patience96@hotmail.com,BERCY,Paris,France,2026-03-20 04:34:45.098836+00:00,2026-03-20 04:34:45.098836+00:00
125,176,Peju,Sokunle,Peju Sokunle,pejutope92@gmail.com,PARIS,Paris,France,2026-03-20 13:58:49.392765+00:00,2026-03-20 13:58:49.392765+00:00
126,177,Oge,Lita,Oge Lita,Ermmaculate97@gmail.com,ABUJA,Fct,Nigeria,2026-03-20 16:46:50.808982+00:00,2026-03-20 16:53:05.596434+00:00
127,178,juliet,chioma,juliet chioma,julietmathew92@gmail.com,ABUJA,Lugbe,Nigeria,2026-03-21 18:43:12.600129+00:00,2026-03-21 18:43:12.600129+00:00

In [ ]:
# import datetime

In [12]:
# in_prog_customers# # for one:
# in_prog_customers['created_at'] = pd.to_datetime(in_prog_customers['created_at'])
# in_prog_customers[in_prog_customers['created_at'] > '2026-03-11']

for col in in_prog_customers.columns:
    if col in ('created_at', 'updated_at'):
        in_prog_customers[col] = pd.to_datetime(in_prog_customers[col])

cols_to_category = ['country', 'is_active',  'postal_code']
in_prog_customers[cols_to_category] = in_prog_customers[cols_to_category].astype('category')

print(in_prog_customers.dtypes)
print(in_prog_customers.columns)
# It should say: datetime64[ns]
# # Another way to do
# cols_to_fix = ['created_at', 'updated_at']
# # This converts both columns at once without an explicit 'for' loop
# in_prog_customers[cols_to_fix] = in_prog_customers[cols_to_fix].apply(pd.to_datetime)


# print(in_prog_customers['country'].memory_usage())
# print(in_prog_customers['country'].astype('category').memory_usage())

id                           int64
first_name                  object
last_name                   object
email                       object
phone                       object
address                     object
city                        object
state                       object
country                   category
postal_code               category
password                    object
is_active                 category
created_at     datetime64[ns, UTC]
updated_at     datetime64[ns, UTC]
fullname                    object
dtype: object
Index(['id', 'first_name', 'last_name', 'email', 'phone', 'address', 'city',
       'state', 'country', 'postal_code', 'password', 'is_active',
       'created_at', 'updated_at', 'fullname'],
      dtype='object')

In [ ]:
customers_recent = in_prog_customers[in_prog_customers['created_at'] >= '2026-03-12']
customers_recent.tail()

In [ ]:
customers_recent.count()
customers_recent.at[1, 'city'] = 'Lagos'

In [13]:
trans_customers = in_prog_customers.loc[:, ['id', 'fullname', 'phone','email', 'address', 'city', 'state',
                                            'country', 'postal_code', 'password', 'is_active','created_at', 'updated_at']]
# trans_customers = customers_recent.loc[:, ['id', 'first_name', 'last_name', 'fullname', 'email', 'city', 'state', 'country', 'created_at', 'updated_at']]

In [ ]:
# trans_customers.to_csv('phoenix_kartify customers')
# trans_customers.head(2)

The "Object" Dtype (The Default)
When Pandas sees text (strings), it defaults to object.

How it works: It stores every single string as a full piece of data in every row.

The Problem: If you have a column called City and "Chicago" appears 1 million times, Pandas stores the full word "Chicago" 1 million separate times. This eats up a massive amount of memory.

2. The "Category" Dtype (The Optimization)
A category tells Pandas: "Hey, there are only a few unique values in this column that repeat over and over."

How it works: Pandas creates a mapping table. It stores the unique words (like "Chicago", "New York") only once and assigns them a tiny number (like 0, 1, 2). In your actual table, it just stores those tiny numbers.

The Benefit: It drastically shrinks the file size and makes sorting/grouping much faster.

# Check memory before
print(chicago_new['Department'].memory_usage())

# Convert to category
chicago_new['Department'] = chicago_new['Department'].astype('category')

# Check memory after (it will be much smaller!)
print(chicago_new['Department'].memory_usage())

In [ ]:
# replacing the values in my initial dictionary list with the new transformed data
dict_list['customers_df'] = trans_customers

In [ ]:
# database = 'KARTDB'
# raw_schema = 'KARTIFY'
# trans_schema = 'KARTIFY_TRANS'

# url = URL(
#     account = 'PPXZJRB-KR90803',
#     user = 'CHEEZY',
#     password = 'Mathematics@999',
#     database = database,
#     # schema = trans_schema,
#     warehouse = 'COMPUTE_WH',
#     role='ACCOUNTADMIN',
# )

# dest_sf_engine = create_engine(url)

In [ ]:
dest_engine.connect()

In [ ]:
trans_customers.to_sql('PHOENIX_CUSTOMERS', dest_sf_engine, schema = trans_schema, if_exists='fail', index=False)

In [ ]:
#### transform the ... table

In [14]:
products_df.info()
products_df['description'].unique()
products_df['is_active'].unique()
products_df.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           15 non-null     int64
 1   category_id  15 non-null     int64
 2   name         15 non-null     object
 3   slug         15 non-null     object
 4   description  15 non-null     object
 5   price        15 non-null     float64
 6   image_url    0 non-null      object
 7   is_active    15 non-null     bool
 8   created_at   15 non-null     datetime64[ns, UTC]
 9   updated_at   15 non-null     datetime64[ns, UTC]
dtypes: bool(1), datetime64[ns, UTC](2), float64(1), int64(2), object(4)
memory usage: 1.2+ KB

,id,category_id,name,slug,description,price,image_url,is_active,created_at,updated_at
0,1,1,Samsung Galaxy A54,samsung-galaxy-a54,Mid-range Android smartphone,299.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,2,1,Wireless Earbuds Pro,wireless-earbuds-pro,Noise-cancelling wireless earbuds,49.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
2,3,1,USB-C Hub 7-in-1,usb-c-hub-7in1,Multiport USB-C adapter,35.00,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00

In [15]:
in_prog_products = products_df.copy()

In [18]:
in_prog_products = in_prog_products.rename(columns = {'name': 'product_name',
                                                     'description': 'product_description',
                                                      'slug': 'prod_slug',
                                                     'id': 'product_id'})
print(in_prog_products.columns)

Index(['product_id', 'category_id', 'product_name', 'prod_slug',
       'product_description', 'price', 'image_url', 'is_active', 'created_at',
       'updated_at'],
      dtype='object')

In [19]:
for col in in_prog_products.columns:
    if col in ('created_at', 'updated_at'):
        in_prog_products[col] = pd.to_datetime(in_prog_products[col])
print(in_prog_products.dtypes)

product_id                           int64
category_id                          int64
product_name                        object
prod_slug                           object
product_description                 object
price                              float64
image_url                           object
is_active                             bool
created_at             datetime64[ns, UTC]
updated_at             datetime64[ns, UTC]
dtype: object

In [ ]:
# col_to_drop = ['prod_slug', 'image_url']
# for cols in col_to_drop:
#     in_prog_products = in_prog_products.drop(columns = col_to_drop)

In [ ]:
# # Just define the list of columns you actually want for your Silver layer
# silver_columns = [
#     'product_id', 'category_id', 'product_name', 
#     'product_description', 'price', 'is_active', 
#     'created_at', 'updated_at'
# ]

# # Use loc to create a clean, filtered dataframe
# trans_products = in_prog_products.loc[:, silver_columns].copy()

In [20]:
trans_products = in_prog_products.loc[:, ['product_id', 'category_id', 'product_name',
                                          'product_description', 'price', 'is_active',
                                          'created_at', 'updated_at']].copy()

In [21]:
trans_products.head()

,product_id,category_id,product_name,product_description,price,is_active,created_at,updated_at
0,1,1,Samsung Galaxy A54,Mid-range Android smartphone,299.99,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,2,1,Wireless Earbuds Pro,Noise-cancelling wireless earbuds,49.99,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
2,3,1,USB-C Hub 7-in-1,Multiport USB-C adapter,35.00,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
3,4,1,Mechanical Keyboard,"TKL mechanical keyboard, red switches",79.99,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
4,5,2,Classic White Tee,100% cotton unisex t-shirt,15.99,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00

In [ ]:
# send to transf layer

You should absolutely use the .loc[] (Selection) method.

In a Medallion Architecture, using .loc[] to explicitly name the columns you want is considered a "Best Practice" for the jump from Bronze to Silver (Transformed).

Here is why .loc[] beats .drop() in this scenario:

1. The "Safety" Factor
.drop() is reactive: If your source database (Bronze) suddenly adds a new column called internal_margin_percentage, your .drop() code won't know about it. That sensitive data will "leak" into your Transformed layer.

.loc[] is proactive: You are creating a "Strict Schema." Only the columns you explicitly list are allowed through the gate. Anything new added at the source is ignored until you decide to add it to your list.

In [ ]:
# next transform = .... table

In [ ]:
# 'coupons_df',  'payments_df', 'shipping_df', 'inventory_df', 'reviews_df'

# categories_df.info()
# categories_df['name'].unique()
# categories_df['is_active'].unique()
# categories_df.head(3)

# orders_df.info()
# orders_df.head(3)
# orders_df['status'].unique()
# orders_df['is_active'].unique()

# coupons_df.info()
# shipping_df.head(3)
# coupons_df['status'].unique()
# coupons_df['is_active'].unique()

# customers_df.info()
# customers_df.head(3)
# customers_df['status'].unique()
# customers_df['is_active'].unique()

# order_items_df.info()
# order_items_df.head(3)
# order_items_df['status'].unique()
# order_items_df['is_active'].unique()

In [ ]:
order_items_df.head(3)

In [ ]:
merged_orders = pd.merge(orders_df, order_items_df, left_on="id", right_on="order_id", how = 'right', suffixes=('_orders', '_items'))
# merged = merged_orders['status'].astype('category') #to change the columns as a category, saves memory
# whats this id in order_items

In [ ]:
# test = build_sales.groupby("order_id")[["total_price", "subtotal"]].sum().reset_index()
# test.head(10)

# test = build_sales.groupby("order_id").agg({
#     'total_price': 'sum',    # Adds up all the items in the order
#     'subtotal': 'first'      # Just takes the value once (since it's the same for all rows in that order)
# }).reset_index()

# test.head(10)

# # Create a difference column
# test['is_accurate'] = test['total_price'].round(2) == test['subtotal'].round(2)

# # Show only the rows where the math doesn't match
# mismatches = test[test['is_accurate'] == False]

# mismatches

### safe to remove the subtotal column

In [ ]:
cols_to_select = ['order_id', 'customer_id', 'product_id', 'quantity', 'unit_price', 'total_price','coupon_id','discount_amount', 'status', 'created_at_items', 'updated_at_items' ]
build_sales = merged_orders[cols_to_select]

# rename merged columns
rename_cols= {'created_at_items' : 'created_at', 
              'updated_at_items' : 'updated_at'}
build_sales = build_sales.rename(columns = rename_cols)
build_sales['status'] = build_sales['status'].astype('category')
build_sales.head(3)

# cols to add = shipping id and payment id from payment and shipping

In [ ]:
# dict_list.keys()

#### pandas profiler

In [ ]:
pip install ydata-profiling

In [ ]:
from ydata_profiling import ProfileReport

# Generate the profile report
profile = ProfileReport(
    customers_df,
    title="Pandas Profiling Report",
    explorative=True,  # Enables more detailed analysis
    minimal=False      # Set to True for faster, lighter reports
)

# Save the report to an HTML file
# profile.to_file("report.html")

# print("✅ Report generated: report.html")

In [ ]:
# profile