Lets practoce Pandas

In [2]:
import pandas as pd

In [3]:
chicago = pd.read_csv('csv_files/chicago.csv')
chicago.head(3)

                Name    Position Title   Department Employee Annual Salary
0    AARON,  ELVIA J  WATER RATE TAKER  WATER MGMNT              $90744.00
1  AARON,  JEFFERY M    POLICE OFFICER       POLICE              $84450.00
2     AARON,  KARINA    POLICE OFFICER       POLICE              $84450.00

In [3]:
chicago.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32063 entries, 0 to 32062
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  object
 3   Employee Annual Salary  32062 non-null  object
dtypes: object(4)
memory usage: 1002.1+ KB

In [32]:
chicago.shape

(32063, 4)

In [4]:
display(chicago)

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...,...
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00
32062,NaN,NaN,NaN,NaN

In [3]:
chicago["Department"].unique()

array(['WATER MGMNT', 'POLICE', 'GENERAL SERVICES', 'CITY COUNCIL',
       'STREETS & SAN', 'OEMC', 'AVIATION', 'FIRE', 'FAMILY & SUPPORT',
       'IPRA', 'PUBLIC LIBRARY', 'BUSINESS AFFAIRS', 'TRANSPORTN',
       'HEALTH', "MAYOR'S OFFICE", 'LAW', 'FINANCE', 'CULTURAL AFFAIRS',
       'COMMUNITY DEVELOPMENT', 'BUILDINGS', 'ANIMAL CONTRL',
       'CITY CLERK', 'BOARD OF ELECTION', 'INSPECTOR GEN', 'TREASURER',
       'DISABILITIES', 'HUMAN RESOURCES', 'DoIT', 'BUDGET & MGMT',
       'PROCUREMENT', 'HUMAN RELATIONS', 'BOARD OF ETHICS',
       'POLICE BOARD', 'ADMIN HEARNG', 'LICENSE APPL COMM', nan],
      dtype=object)

In [5]:
chicago.tail(5)

,Name,Position Title,Department,Employee Annual Salary
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00
32062,NaN,NaN,NaN,NaN

In [6]:
chicago.sample(10)

,Name,Position Title,Department,Employee Annual Salary
11087,"GUTRICH, JOHN S",POLICE OFFICER,POLICE,$87384.00
4382,"CELIO, VINCENT",POLICE OFFICER,POLICE,$84450.00
11262,"HALLORAN, BRIAN M",POLICE OFFICER,POLICE,$84450.00
14918,"KING, RICKEY",CONSTRUCTION LABORER,WATER MGMNT,$81536.00
1222,"BAEZA JR, RAUL",POLICE OFFICER,POLICE,$87384.00
13360,"JACOB, CHRISTINE",PROGRAM COORD - SPECIAL EVENTS,CULTURAL AFFAIRS,$91476.00
31612,"YANAGIDATE, ALAN I",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,$100884.00
4371,"CEGIELSKI, JOHN A",LIEUTENANT,FIRE,$104628.00
4858,"CLARK, FRANK",MOTOR TRUCK DRIVER,STREETS & SAN,$73964.80
18904,"MICHAELS, BRADLEY S",POLICE OFFICER,POLICE,$66606.00

whan you add the random_state argument,its because you want to have that random sample kind of saved.
You can use random_state for reproducibility.

In [7]:
chicago.sample(5, random_state = 1)

,Name,Position Title,Department,Employee Annual Salary
28618,"TIMMEL, MARK C",POLICE OFFICER,POLICE,$90618.00
16924,"LYLE, JEFFREY A",COORD OF SPECIAL EVENTS LIAISON,FIRE,$157776.00
7210,"DOMINGUEZ, VANESSA",POLICE OFFICER,POLICE,$66606.00
9253,"FUNG, JIMMY K",SANITATION LABORER,STREETS & SAN,$73840.00
23131,"QUARTERMAN, STACEY A",POLICE OFFICER,POLICE,$90618.00

In [8]:
chicago.sample(5, random_state = 5)

,Name,Position Title,Department,Employee Annual Salary
776,"ANDRAS, GREGORY A",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,$98016.00
15025,"KLINGER, FRED",OPERATING ENGINEER-GROUP C,WATER MGMNT,$93745.60
5571,"COREAS, RAFAEL E",STAFF ASST TO THE ALDERMAN,CITY COUNCIL,$72684.00
10963,"GUERRERO, MIRIAM",SENIOR LIBRARY CLERK,PUBLIC LIBRARY,$46896.00
7503,"DUDA, BARTOSZ",POLICE OFFICER,POLICE,$66606.00

In [9]:
chicago.sample(5, random_state = 1)

,Name,Position Title,Department,Employee Annual Salary
28618,"TIMMEL, MARK C",POLICE OFFICER,POLICE,$90618.00
16924,"LYLE, JEFFREY A",COORD OF SPECIAL EVENTS LIAISON,FIRE,$157776.00
7210,"DOMINGUEZ, VANESSA",POLICE OFFICER,POLICE,$66606.00
9253,"FUNG, JIMMY K",SANITATION LABORER,STREETS & SAN,$73840.00
23131,"QUARTERMAN, STACEY A",POLICE OFFICER,POLICE,$90618.00

In [10]:
chicago.sample(5, random_state = 3)

,Name,Position Title,Department,Employee Annual Salary
20251,"NASH, DWIGHT",SEWER BRICKLAYER,WATER MGMNT,$91062.40
7171,"DOHERTY, WILLIAM P",MOTOR TRUCK DRIVER,AVIATION,$72862.40
13860,"JOHNSON, MELVIN",MACHINIST (AUTOMOTIVE),GENERAL SERVICES,$94328.00
29952,"WALKER, JEAN",SENIOR DATA ENTRY OPERATOR,POLICE,$62004.00
262,"AICH, ABRAHAM A",POLICE OFFICER,POLICE,$87384.00

In [11]:
chicago.sample(5, random_state = 5)

,Name,Position Title,Department,Employee Annual Salary
776,"ANDRAS, GREGORY A",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,$98016.00
15025,"KLINGER, FRED",OPERATING ENGINEER-GROUP C,WATER MGMNT,$93745.60
5571,"COREAS, RAFAEL E",STAFF ASST TO THE ALDERMAN,CITY COUNCIL,$72684.00
10963,"GUERRERO, MIRIAM",SENIOR LIBRARY CLERK,PUBLIC LIBRARY,$46896.00
7503,"DUDA, BARTOSZ",POLICE OFFICER,POLICE,$66606.00

In [12]:
chicago["Department"].sample(5, random_state = 1)

28618           POLICE
16924             FIRE
7210            POLICE
9253     STREETS & SAN
23131           POLICE
Name: Department, dtype: object

location[rows, columns]
iloc(integer locations)

In [13]:
chicago.loc[[7210, 9253, 16924]]

,Name,Position Title,Department,Employee Annual Salary
7210,"DOMINGUEZ, VANESSA",POLICE OFFICER,POLICE,$66606.00
9253,"FUNG, JIMMY K",SANITATION LABORER,STREETS & SAN,$73840.00
16924,"LYLE, JEFFREY A",COORD OF SPECIAL EVENTS LIAISON,FIRE,$157776.00

In [14]:
chicago.loc[5:8, ["Name", "Department"]]

                   Name     Department
5       ABARCA,  ANABEL   CITY COUNCIL
6     ABARCA,  EMMANUEL  STREETS & SAN
7     ABASCAL,  REECE E           OEMC
8  ABBASI,  CHRISTOPHER   CITY COUNCIL

In [15]:
chicago.iloc[5:8, [0, 2]]

                Name     Department
5    ABARCA,  ANABEL   CITY COUNCIL
6  ABARCA,  EMMANUEL  STREETS & SAN
7  ABASCAL,  REECE E           OEMC

In [33]:
# This tells pandas to pandas to replace the index comlumn by the values from that column
# you can use it if you dont want to specify using the index, just want to use the department.
# better to use set_index() to use the depatment as index coluln, instead of creating another clolumn
chicago.index = chicago.Department
chicago.index = chicago["Department"]
chicago.head(3)

SyntaxError: invalid syntax (3841951885.py, line 5)

In [26]:
# When you do this, you can then get just the values in that department, because its now the index
chicago.loc["POLICE"]

# chicago.loc["CITY COUNCIL": "OEMC"]
# but the above doesnt work because: Pandas needs to know exactly where to start and exactly where to stop. If 'CITY COUNCIL' appears more than once in your index.
# so better to sort it first.
# chicago = chicago.reset_index()

chicago.loc["CITY COUNCIL", "Name"]

Department
CITY COUNCIL         ABARCA,  ANABEL
CITY COUNCIL    ABBASI,  CHRISTOPHER
CITY COUNCIL       ACEVEDO,  ELIAS M
CITY COUNCIL       ADELMAN,  BRUCE E
CITY COUNCIL      AHUILE,  CECILIA T
                        ...
CITY COUNCIL         YANCY,  ETHEL M
CITY COUNCIL        ZAHDAN,  MOEEN D
CITY COUNCIL    ZALEWSKI,  MICHAEL R
CITY COUNCIL           ZARIC,  MARKO
CITY COUNCIL     ZIEGLER,  BARBARA G
Name: Name, Length: 396, dtype: object

In [4]:
chicago.head(3)
chicago = chicago.reset_index()

In [7]:
chicago.head(3)

                Name    Position Title   Department Employee Annual Salary
0    AARON,  ELVIA J  WATER RATE TAKER  WATER MGMNT              $90744.00
1  AARON,  JEFFERY M    POLICE OFFICER       POLICE              $84450.00
2     AARON,  KARINA    POLICE OFFICER       POLICE              $84450.00

In [8]:
chicago.loc[0, "Department"] = "POLICE"

In [9]:
chicago.head(3)

                Name    Position Title Department Employee Annual Salary
0    AARON,  ELVIA J  WATER RATE TAKER     POLICE              $90744.00
1  AARON,  JEFFERY M    POLICE OFFICER     POLICE              $84450.00
2     AARON,  KARINA    POLICE OFFICER     POLICE              $84450.00

In [12]:
chicago.loc[0:3, "Department"] = "WATER"
chicago.head(3)

                Name    Position Title Department Employee Annual Salary
0    AARON,  ELVIA J  WATER RATE TAKER      WATER              $90744.00
1  AARON,  JEFFERY M    POLICE OFFICER      WATER              $84450.00
2     AARON,  KARINA    POLICE OFFICER      WATER              $84450.00

In [17]:
# iat and at only helps grab single values, so mpst prefer to use loc and iloc

chicago.at[0, "Position Title"]
chicago.iat[0, 1]

'WATER RATE TAKER'

In [20]:
# chicago.Position Title #when its multiple values cant pick it up
chicago["Position Title"]

0                WATER RATE TAKER
1                  POLICE OFFICER
2                  POLICE OFFICER
3        CHIEF CONTRACT EXPEDITER
4               CIVIL ENGINEER IV
                   ...
32058              POLICE OFFICER
32059              POLICE OFFICER
32060              POLICE OFFICER
32061     CHIEF DATA BASE ANALYST
32062                         NaN
Name: Position Title, Length: 32063, dtype: object

In [10]:
# chicago.sort_values("Employee Annual Salary")
chicago.sort_values("Department")
# chicago.sort_values(["Employee Annual Salary", "Department"] , ascending=False)
chicago.sort_values(["Employee Annual Salary", "Department"] , ascending=[1,0]) #salary is false while department is true

,Name,Position Title,Department,Employee Annual Salary
15102,"KOCH, STEVEN",ADMINISTRATIVE SECRETARY,MAYOR'S OFFICE,$0.96
395,"ALFICH, FRED T",HOISTING ENGINEER,WATER MGMNT,$100048.00
396,"ALFICH, SCOTT",HOISTING ENGINEER,WATER MGMNT,$100048.00
500,"ALMANZA, JESUS",HOISTING ENGINEER,WATER MGMNT,$100048.00
903,"ARCIERI, ROCCO",HOISTING ENGINEER,WATER MGMNT,$100048.00
...,...,...,...,...
23475,"RAYBORN, BILLY",FOREMAN OF ELECTRICAL MECHANICS,AVIATION,$99840.00
25082,"RYAN, DANIEL P",FOREMAN OF ELECTRICAL MECHANICS,AVIATION,$99840.00
27407,"STARKS, ALVIN D",SERGEANT AT ARMS,CITY COUNCIL,$99936.00
23434,"RAPELYEA, SEAN M",ADMINISTRATIVE ASST,MAYOR'S OFFICE,$99996.00
32062,NaN,NaN,NaN,NaN

In [24]:
#for iteration, loses some memory performznce beneffits

# for index, row in chicago.iterrows():
#     print(index)
#     print(row)
#     print("\n")


for index, row in chicago.iterrows():
    print(index)
    print(row[3])
    print("\n")

0
$90744.00


1
$84450.00


2
$84450.00


3
$89880.00


4
$106836.00


5
$70764.00


6
$41849.60


7
$20051.20


8
$49452.00


9
$93600.00


10
$100320.00


11
$90618.00


12
$2756.00


13
$46896.00


14
$73920.00


15
$74028.00


16
$81588.00


17
$99228.00


18
$81588.00


19
$88596.00


20
$108228.00


21
$92682.00


22
$111474.00


23
$17846.40


24
$93600.00


25
$58536.00


26
$41849.60


27
$2756.00


28
$87384.00


29
$70380.00


30
$72862.40


31
$25334.40


32
$46668.00


33
$106836.00


34
$106836.00


35
$98616.00


36
$70380.00


37
$59652.00


38
$73840.00


39
$93240.00


40
$125190.00


41
$72862.40


42
$86538.00


43
$91062.40


44
$75961.60


45
$98799.96


46
$68028.00


47
$2756.00


48
$96414.00


49
$87384.00


50
$93600.00


51
$78204.00


52
$46668.00


53
$98280.00


54
$46668.00


55
$89676.00


56
$91752.00


57
$81536.00


58
$84450.00


59
$84450.00


60
$115356.00


61
$73964.80


62
$55008.00


63
$81588.00


64
$84450.00


65
$87384.00


66
$93240.00


67
$84450.00


68
$94530.00


69
$20004.00


70
$66606.00


71
$118248.00


72
$74028.00


73
$81588.00


74
$84450.00


75
$81536.00


76
$90618.00


77
$51216.00


78
$87384.00


79
$98016.00


80
$87324.00


81
$87384.00


82
$65472.00


83
$87384.00


84
$84450.00


85
$84450.00


86
$87384.00


87
$124572.00


88
$87384.00


89
$92682.00


90
$70380.00


91
$17024.80


92
$46668.00


93
$90618.00


94
$46668.00


95
$67452.00


96
$87384.00


97
$46668.00


98
$73840.00


99
$56928.00


100
$81536.00


101
$81588.00


102
$84450.00


103
$73840.00


104
$12844.00


105
$65894.40


106
$90918.00


107
$43222.40


108
$84450.00


109
$98016.00


110
$88410.00


111
$72862.40


112
$86538.00


113
$76876.80


114
$93240.00


115
$83340.00


116
$57696.00


117
$58800.00


118
$97812.00


119
$81588.00


120
$18699.20


121
$81536.00


122
$51516.00


123
$73840.00


124
$62496.00


125
$74676.00


126
$81536.00


127
$98016.00


128
$90618.00


129
$86538.00


130
$54654.00


131
$74028.00


132
$64992.00


133
$13520.00


134
$66606.00


135
$98016.00


136
$44824.00


137
$81948.00


138
$72862.40


139
$68556.00


140
$110970.00


141
$100470.00


142
$94868.80


143
$14684.80


144
$81588.00


145
$97812.00


146
$91476.00


147
$106836.00


148
$74676.00


149
$94584.00


150
$87384.00


151
$59184.00


152
$84450.00


153
$81536.00


154
$72862.40


155
$54000.00


156
$16317.60


157
$67452.00


158
$121464.00


159
$109272.00


160
$81588.00


161
$111474.00


162
$72492.00


163
$84450.00


164
$120192.00


165
$19572.00


166
$97812.00


167
$97812.00


168
$73382.40


169
$97812.00


170
$71292.00


171
$58908.00


172
$75240.00


173
$93240.00


174
$93840.00


175
$25334.40


176
$81588.00


177
$87384.00


178
$71292.00


179
$90618.00


180
$100320.00


181
$107988.00


182
$119880.00


183
$87384.00


184
$99840.00


185
$122856.00


186
$84450.00


187
$93240.00


188
$72862.40


189
$100884.00


190
$98016.00


191
$84450.00


192
$59772.00


193
$111474.00


194
$84450.00


195
$73840.00


196
$73840.00


197
$74028.00


198
$74028.00


199
$70380.00


200
$89568.00


201
$65028.00


202
$109608.00


203
$99552.00


204
$73840.00


205
$68028.00


206
$87324.00


207
$72862.40


208
$68688.00


209
$80196.00


210
$14570.40


211
$72862.40


212
$62004.00


213
$104628.00


214
$50472.00


215
$87384.00


216
$81588.00


217
$68568.00


218
$72862.40


219
$46668.00


220
$73840.00


221
$98799.96


222
$84450.00


223
$70380.00


224
$77670.00


225
$93240.00


226
$81588.00


227
$73840.00


228
$87384.00


229
$81588.00


230
$94200.00


231
$81588.00


232
$100884.00


233
$95178.00


234
$98280.00


235
$72862.40


236
$81588.00


237
$84450.00


238
$98799.96


239
$93240.00


240
$89676.00


241
$74304.00


242
$87384.00


243
$100320.00


244
$87384.00


245
$90618.00


246
$46668.00


247
$70380.00


248
$110970.00


249
$81588.00


250
$69825.60


251
$63840.00


252
$134340.00


253
$113664.00


254
$54360.00


255
$46668.00


256
$120444.00


257
$85764.00


258
$82044.00


259
$46896.00


260
$56508.00


261
$50460.00


262
$87384.00


263
$132780.00


264
$49140.00


265
$107280.00


266
$87384.00


267
$87384.00


268
$70380.00


269
$48240.00


270
$72862.40


271
$72862.40


272
$72862.40


273
$8580.00


274
$67872.00


275
$95178.00


276
$92682.00


277
$90618.00


278
$87576.00


279
$98675.20


280
$81588.00


281
$20051.20


282
$65004.00


283
$93240.00


284
$84450.00


285
$73840.00


286
$72862.40


287
$81588.00


288
$81588.00


289
$71820.00


290
$90618.00


291
$74028.00


292
$90618.00


293
$90618.00


294
$81948.00


295
$2756.00


296
$84450.00


297
$82044.00


298
$98016.00


299
$94328.00


300
$90618.00


301
$84450.00


302
$74028.00


303
$87384.00


304
$84450.00


305
$43222.40


306
$68028.00


307
$96120.00


308
$81948.00


309
$81588.00


310
$66606.00


311
$70380.00


312
$69324.00


313
$90618.00


314
$89568.00


315
$120036.84


316
$72862.40


317
$74028.00


318
$66456.00


319
$85764.00


320
$90918.00


321
$74131.20


322
$46668.00


323
$94328.00


324
$85704.00


325
$100320.00


326
$99672.00


327
$84450.00


328
$81536.00


329
$73840.00


330
$65472.00


331
$17846.40


332
$14060.80


333
$81948.00


334
$53955.20


335
$58908.00


336
$86538.00


337
$81588.00


338
$84450.00


339
$96120.00


340
$87384.00


341
$98799.96


342
$81588.00


343
$87384.00


344
$81536.00


345
$93240.00


346
$104628.00


347
$98016.00


348
$93240.00


349
$62580.00


350
$104628.00


351
$87384.00


352
$93745.60


353
$74028.00


354
$66606.00


355
$27228.00


356
$70380.00


357
$90618.00


358
$89568.00


359
$98280.00


360
$68028.00


361
$86700.00


362
$84450.00


363
$70380.00


364
$88656.00


365
$107988.00


366
$65582.40


367
$81536.00


368
$98016.00


369
$170112.00


370
$81588.00


371
$87384.00


372
$18699.20


373
$68568.00


374
$121464.00


375
$87384.00


376
$90618.00


377
$84450.00


378
$17846.40


379
$73840.00


380
$2756.00


381
$47316.00


382
$33876.00


383
$20498.40


384
$81588.00


385
$95088.00


386
$57696.00


387
$75048.00


388
$87384.00


389
$74028.00


390
$90618.00


391
$81588.00


392
$87384.00


393
$82560.00


394
$75960.00


395
$100048.00


396
$100048.00


397
$100884.00


398
$17846.40


399
$65592.00


400
$28808.00


401
$84450.00


402
$89568.00


403
$84450.00


404
$84450.00


405
$106836.00


406
$106836.00


407
$18699.20


408
$81536.00


409
$87384.00


410
$98675.20


411
$69825.60


412
$68028.00


413
$73840.00


414
$81588.00


415
$100656.00


416
$81588.00


417
$98675.20


418
$104628.00


419
$46668.00


420
$81536.00


421
$9640.80


422
$89880.00


423
$58764.00


424
$106980.00


425
$91000.00


426
$98675.20


427
$16317.60


428
$84450.00


429
$90918.00


430
$62004.00


431
$107988.00


432
$64992.00


433
$14570.40


434
$82044.00


435
$100320.00


436
$44824.00


437
$107988.00


438
$107988.00


439
$84450.00


440
$87384.00


441
$90618.00


442
$92682.00


443
$95178.00


444
$66606.00


445
$20051.20


446
$74304.00


447
$93240.00


448
$90618.00


449
$87384.00


450
$101442.00


451
$107988.00


452
$78204.00


453
$98016.00


454
$90618.00


455
$97812.00


456
$93240.00


457
$54360.00


458
$59184.00


459
$22568.00


460
$98016.00


461
$73840.00


462
$88410.00


463
$64212.00


464
$87384.00


465
$17846.40


466
$25334.40


467
$65592.00


468
$84450.00


469
$90618.00


470
$84450.00


471
$72862.40


472
$94328.00


473
$72862.40


474
$72862.40


475
$97812.00


476
$44808.00


477
$71905.60


478
$20051.20


479
$68028.00


480
$81588.00


481
$83824.00


482
$73840.00


483
$68568.00


484
$73840.00


485
$156360.00


486
$95178.00


487
$74676.00


488
$44574.40


489
$73840.00


490
$72862.40


491
$110970.00


492
$78468.00


493
$94328.00


494
$59652.00


495
$104628.00


496
$72862.40


497
$66606.00


498
$84450.00


499
$59652.00


500
$100048.00


501
$84450.00


502
$84924.00


503
$90618.00


504
$71292.00


505
$100884.00


506
$71292.00


507
$83340.00


508
$84450.00


509
$87384.00


510
$66606.00


511
$98016.00


512
$100344.00


513
$74028.00


514
$111474.00


515
$17586.40


516
$53890.20


517
$84450.00


518
$87384.00


519
$77670.00


520
$88452.00


521
$75276.00


522
$98016.00


523
$71232.00


524
$84450.00


525
$72862.40


526
$70380.00


527
$108204.00


528
$70380.00


529
$111474.00


530
$89544.00


531
$94824.00


532
$16317.60


533
$72862.40


534
$84450.00


535
$94584.00


536
$87324.00


537
$109272.00


538
$81536.00


539
$68028.00


540
$56544.00


541
$78204.00


542
$20051.20


543
$101442.00


544
$46668.00


545
$81588.00


546
$81588.00


547
$74028.00


548
$46668.00


549
$145116.00


550
$136836.00


551
$93240.00


552
$81588.00


553
$68688.00


554
$102440.00


555
$72862.40


556
$87384.00


557
$68028.00


558
$81588.00


559
$101442.00


560
$73840.00


561
$78000.00


562
$73840.00


563
$87384.00


564
$87384.00


565
$85704.00


566
$54654.00


567
$94530.00


568
$84450.00


569
$94530.00


570
$98799.96


571
$75960.00


572
$104628.00


573
$81588.00


574
$66888.00


575
$25898.60


576
$61620.00


577
$90918.00


578
$70380.00


579
$77670.00


580
$58608.00


581
$98016.00


582
$81588.00


583
$70380.00


584
$104628.00


585
$66606.00


586
$72862.40


587
$81588.00


588
$87384.00


589
$72862.40


590
$66606.00


591
$110970.00


592
$73840.00


593
$74028.00


594
$74028.00


595
$46668.00


596
$72862.40


597
$94200.00


598
$48648.00


599
$72862.40


600
$22568.00


601
$65582.40


602
$111474.00


603
$81588.00


604
$73840.00


605
$101442.00


606
$107988.00


607
$81588.00


608
$132876.00


609
$44808.00


610
$54654.00


611
$85740.00


612
$73840.00


613
$66606.00


614
$60780.00


615
$46668.00


616
$72862.40


617
$90618.00


618
$81948.00


619
$109008.00


620
$87384.00


621
$12480.00


622
$62004.00


623
$72862.40


624
$87384.00


625
$125190.00


626
$94584.00


627
$100884.00


628
$84450.00


629
$86538.00


630
$66606.00


631
$100884.00


632
$116604.00


633
$94824.00


634
$106440.00


635
$86538.00


636
$65894.40


637
$104328.00


638
$93600.00


639
$105120.00


640
$87384.00


641
$84450.00


642
$84450.00


643
$72862.40


644
$72862.40


645
$102702.00


646
$119952.00


647
$46668.00


648
$25334.40


649
$87384.00


650
$90618.00


651
$85740.00


652
$54360.00


653
$65172.00


654
$87384.00


655
$65472.00


656
$56544.00


657
$74028.00


658
$108368.00


659
$97092.00


660
$81588.00


661
$113376.00


662
$101280.00


663
$74028.00


664
$82728.00


665
$74028.00


666
$81588.00


667
$14060.80


668
$104628.00


669
$79740.00


670
$74028.00


671
$82044.00


672
$95178.00


673
$84450.00


674
$84450.00


675
$72862.40


676
$111474.00


677
$105084.00


678
$100320.00


679
$94584.00


680
$125190.00


681
$72862.40


682
$73964.80


683
$73840.00


684
$72862.40


685
$109272.00


686
$2756.00


687
$74028.00


688
$98016.00


689
$68028.00


690
$84450.00


691
$84450.00


692
$74028.00


693
$89676.00


694
$92964.00


695
$91062.40


696
$81588.00


697
$115704.00


698
$84450.00


699
$72862.40


700
$87384.00


701
$19572.80


702
$102440.00


703
$84450.00


704
$89568.00


705
$91476.00


706
$20051.20


707
$87384.00


708
$103740.00


709
$74304.00


710
$81588.00


711
$89568.00


712
$79596.00


713
$108534.40


714
$88596.00


715
$100884.00


716
$93240.00


717
$93240.00


718
$68028.00


719
$86538.00


720
$51492.00


721
$87384.00


722
$125190.00


723
$81536.00


724
$98706.00


725
$136170.00


726
$90618.00


727
$100884.00


728
$89544.00


729
$69240.00


730
$109008.00


731
$98675.20


732
$81536.00


733
$59772.00


734
$72862.40


735
$98016.00


736
$93600.00


737
$87384.00


738
$101442.00


739
$74028.00


740
$8580.00


741
$20051.20


742
$93240.00


743
$84450.00


744
$72862.40


745
$64992.00


746
$75960.00


747
$39204.00


748
$94584.00


749
$91752.00


750
$86538.00


751
$2756.00


752
$94530.00


753
$73840.00


754
$89676.00


755
$104628.00


756
$93745.60


757
$73840.00


758
$68556.00


759
$90618.00


760
$81536.00


761
$68568.00


762
$73840.00


763
$121464.00


764
$87384.00


765
$93240.00


766
$84450.00


767
$18699.20


768
$22568.00


769
$94584.00


770
$89568.00


771
$87384.00


772
$81588.00


773
$90618.00


774
$100884.00


775
$72862.40


776
$98016.00


777
$67452.00


778
$90618.00


779
$107988.00


780
$74028.00


781
$65172.00


782
$73840.00


783
$74028.00


784
$128988.00


785
$81588.00


786
$111474.00


787
$98799.96


788
$81536.00


789
$13520.00


790
$72862.40


791
$90618.00


792
$83408.00


793
$81588.00


794
$110088.00


795
$84450.00


796
$125190.00


797
$84450.00


798
$91752.00


799
$110970.00


800
$64524.00


801
$84450.00


802
$46668.00


803
$162684.00


804
$62496.00


805
$39096.00


806
$95460.00


807
$14060.80


808
$106980.00


809
$81588.00


810
$90618.00


811
$70380.00


812
$87324.00


813
$51504.00


814
$90618.00


815
$66606.00


816
$89400.00


817
$110970.00


818
$90618.00


819
$73382.40


820
$73840.00


821
$103644.00


822
$90918.00


823
$87384.00


824
$90618.00


825
$51924.00


826
$62004.00


827
$100080.00


828
$90618.00


829
$86538.00


830
$98016.00


831
$66768.00


832
$56544.00


833
$81588.00


834
$90618.00


835
$107988.00


836
$157776.00


837
$64992.00


838
$72862.40


839
$72862.40


840
$81588.00


841
$112308.00


842
$72862.40


843
$88410.00


844
$81588.00


845
$53172.00


846
$74676.00


847
$89568.00


848
$84450.00


849
$109200.00


850
$87324.00


851
$72862.40


852
$72862.40


853
$102702.00


854
$87384.00


855
$51912.00


856
$87384.00


857
$95088.00


858
$22557.60


859
$81588.00


860
$57324.00


861
$85280.00


862
$74028.00


863
$72862.40


864
$89880.00


865
$108534.40


866
$98675.20


867
$81588.00


868
$20051.20


869
$64992.00


870
$59652.00


871
$73840.00


872
$76377.60


873
$90228.00


874
$122676.00


875
$77670.00


876
$74028.00


877
$93745.60


878
$73840.00


879
$104628.00


880
$74028.00


881
$16395.60


882
$87384.00


883
$59652.00


884
$65472.00


885
$95178.00


886
$87324.00


887
$49512.00


888
$89568.00


889
$81536.00


890
$81536.00


891
$77670.00


892
$98016.00


893
$72862.40


894
$81588.00


895
$72862.40


896
$68028.00


897
$72862.40


898
$74028.00


899
$81588.00


900
$48921.60


901
$69240.00


902
$74028.00


903
$100048.00


904
$87384.00


905
$62580.00


906
$73382.40


907
$89544.00


908
$87384.00


909
$84450.00


910
$81588.00


911
$84924.00


912
$90288.00


913
$81588.00


914
$87384.00


915
$81536.00


916
$81588.00


917
$109993.92


918
$13520.00


919
$73840.00


920
$56544.00


921
$87384.00


922
$97812.00


923
$92682.00


924
$97812.00


925
$18699.20


926
$73840.00


927
$74028.00


928
$59184.00


929
$162684.00


930
$54564.00


931
$111474.00


932
$98616.00


933
$84450.00


934
$63840.00


935
$81588.00


936
$74028.00


937
$74028.00


938
$84450.00


939
$94200.00


940
$83340.00


941
$89568.00


942
$81588.00


943
$84450.00


944
$84450.00


945
$90744.00


946
$72862.40


947
$74304.00


948
$91062.40


949
$72862.40


950
$47316.00


951
$46896.00


952
$84450.00


953
$87384.00


954
$93240.00


955
$109200.00


956
$16395.60


957
$98016.00


958
$73840.00


959
$2756.00


960
$87384.00


961
$100656.00


962
$51516.00


963
$92248.00


964
$18699.20


965
$59184.00


966
$68028.00


967
$75240.00


968
$110970.00


969
$18699.20


970
$89544.00


971
$92682.00


972
$87384.00


973
$72862.40


974
$145116.00


975
$99840.00


976
$72862.40


977
$81536.00


978
$94584.00


979
$93600.00


980
$93600.00


981
$87384.00


982
$68028.00


983
$56544.00


984
$109200.00


985
$90618.00


986
$73840.00


987
$66606.00


988
$92682.00


989
$64992.00


990
$73840.00


991
$86538.00


992
$118248.00


993
$74028.00


994
$70380.00


995
$58764.00


996
$82044.00


997
$58608.00


998
$34840.00


999
$109548.00


1000
$46896.00


1001
$86538.00


1002
$81588.00


1003
$109272.00


1004
$87384.00


1005
$74676.00


1006
$84450.00


1007
$93240.00


1008
$81588.00


1009
$68028.00


1010
$84450.00


1011
$87384.00


1012
$87384.00


1013
$100320.00


1014
$49140.00


1015
$73840.00


1016
$72862.40


1017
$44808.00


1018
$67452.00


1019
$121464.00


1020
$43201.60


1021
$98016.00


1022
$94328.00


1023
$72862.40


1024
$101442.00


1025
$86538.00


1026
$75960.00


1027
$90618.00


1028
$89676.00


1029
$104628.00


1030
$89568.00


1031
$92248.00


1032
$115704.00


1033
$160692.00


1034
$100172.76


1035
$81588.00


1036
$91476.00


1037
$68556.00


1038
$44820.00


1039
$113664.00


1040
$43201.60


1041
$81588.00


1042
$74028.00


1043
$111474.00


1044
$66780.00


1045
$54360.00


1046
$62496.00


1047
$81588.00


1048
$91362.00


1049
$81536.00


1050
$87384.00


1051
$17024.80


1052
$94404.00


1053
$70380.00


1054
$82044.00


1055
$84450.00


1056
$77670.00


1057
$18699.20


1058
$90618.00


1059
$102084.00


1060
$73840.00


1061
$59652.00


1062
$39204.00


1063
$90618.00


1064
$87384.00


1065
$63840.00


1066
$88788.00


1067
$78204.00


1068
$73152.00


1069
$72862.40


1070
$107988.00


1071
$84450.00


1072
$66606.00


1073
$74028.00


1074
$87384.00


1075
$94328.00


1076
$72862.40


1077
$58908.00


1078
$62496.00


1079
$82044.00


1080
$100248.00


1081
$73840.00


1082
$87384.00


1083
$73840.00


1084
$50256.00


1085
$118020.00


1086
$81588.00


1087
$87384.00


1088
$70380.00


1089
$106836.00


1090
$72862.40


1091
$84450.00


1092
$84450.00


1093
$2756.00


1094
$87408.00


1095
$94584.00


1096
$118248.00


1097
$88410.00


1098
$66606.00


1099
$107988.00


1100
$74988.00


1101
$43201.60


1102
$90618.00


1103
$87384.00


1104
$87384.00


1105
$81536.00


1106
$71820.00


1107
$62004.00


1108
$79596.00


1109
$68028.00


1110
$117333.00


1111
$68568.00


1112
$90618.00


1113
$103716.00


1114
$45000.00


1115
$72862.40


1116
$20051.20


1117
$90618.00


1118
$92682.00


1119
$81588.00


1120
$73840.00


1121
$82500.00


1122
$90618.00


1123
$84450.00


1124
$87384.00


1125
$68556.00


1126
$89568.00


1127
$12844.00


1128
$70380.00


1129
$81588.00


1130
$137076.00


1131
$72862.40


1132
$111474.00


1133
$17024.80


1134
$81588.00


1135
$72862.40


1136
$98016.00


1137
$81536.00


1138
$95820.00


1139
$84450.00


1140
$91752.00


1141
$125190.00


1142
$73224.00


1143
$74028.00


1144
$17846.40


1145
$72862.40


1146
$81536.00


1147
$74028.00


1148
$66606.00


1149
$43668.00


1150
$71820.00


1151
$59184.00


1152
$46668.00


1153
$91000.00


1154
$91362.00


1155
$58281.60


1156
$94584.00


1157
$107988.00


1158
$57834.00


1159
$68568.00


1160
$72862.40


1161
$110970.00


1162
$88656.00


1163
$78948.00


1164
$51516.00


1165
$106980.00


1166
$82560.00


1167
$74028.00


1168
$56544.00


1169
$73840.00


1170
$81536.00


1171
$74028.00


1172
$64992.00


1173
$89568.00


1174
$70380.00


1175
$104628.00


1176
$104628.00


1177
$73840.00


1178
$56544.00


1179
$89676.00


1180
$66606.00


1181
$53172.00


1182
$84450.00


1183
$87408.00


1184
$87384.00


1185
$73840.00


1186
$84450.00


1187
$54654.00


1188
$84450.00


1189
$116784.00


1190
$94328.00


1191
$84450.00


1192
$84450.00


1193
$46668.00


1194
$98799.96


1195
$90618.00


1196
$81948.00


1197
$104628.00


1198
$90618.00


1199
$87384.00


1200
$102702.00


1201
$66606.00


1202
$98016.00


1203
$90618.00


1204
$87384.00


1205
$25898.60


1206
$98675.20


1207
$75961.60


1208
$81536.00


1209
$80004.00


1210
$97812.00


1211
$97812.00


1212
$16317.60


1213
$98016.00


1214
$90618.00


1215
$87384.00


1216
$38748.00


1217
$81536.00


1218
$84450.00


1219
$84450.00


1220
$59184.00


1221
$84450.00


1222
$87384.00


1223
$71820.00


1224
$72862.40


1225
$70380.00


1226
$72862.40


1227
$93240.00


1228
$99228.00


1229
$104244.00


1230
$100884.00


1231
$81536.00


1232

C:\Users\patie\AppData\Local\Temp\ipykernel_15856\1246055364.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(row[3])

1654
$107988.00


1655
$81536.00


1656
$84876.00


1657
$90618.00


1658
$74676.00


1659
$94584.00


1660
$13520.00


1661
$24000.00


1662
$64596.00


1663
$89568.00


1664
$98800.00


1665
$72862.40


1666
$72862.40


1667
$73840.00


1668
$72862.40


1669
$81588.00


1670
$110088.00


1671
$87384.00


1672
$58908.00


1673
$136170.00


1674
$97812.00


1675
$66780.00


1676
$82560.00


1677
$93240.00


1678
$135936.00


1679
$87384.00


1680
$87384.00


1681
$87384.00


1682
$88596.00


1683
$86538.00


1684
$74028.00


1685
$46668.00


1686
$87384.00


1687
$82560.00


1688
$100320.00


1689
$101442.00


1690
$81588.00


1691
$72862.40


1692
$81536.00


1693
$67766.40


1694
$100344.00


1695
$108228.00


1696
$93745.60


1697
$94584.00


1698
$84450.00


1699
$66780.00


1700
$74028.00


1701
$97812.00


1702
$89568.00


1703
$87384.00


1704
$93240.00


1705
$162684.00


1706
$65894.40


1707
$84450.00


1708
$111474.00


1709
$84450.00


1710
$129096.00


1711
$87384.00


1712
$116208.00


1713
$71292.00


1714
$72862.40


1715
$43201.60


1716
$121068.00


1717
$87384.00


1718
$125190.00


1719
$95178.00


1720
$117264.00


1721
$87384.00


1722
$97812.00


1723
$84450.00


1724
$43201.60


1725
$93600.00


1726
$87384.00


1727
$98016.00


1728
$43201.60


1729
$22568.00


1730
$74028.00


1731
$98016.00


1732
$72862.40


1733
$90618.00


1734
$97812.00


1735
$43201.60


1736
$90618.00


1737
$91704.00


1738
$25898.60


1739
$91362.00


1740
$87384.00


1741
$87384.00


1742
$73500.00


1743
$82044.00


1744
$81536.00


1745
$129156.00


1746
$87384.00


1747
$113598.00


1748
$13520.00


1749
$87384.00


1750
$2756.00


1751
$94584.00


1752
$117894.00


1753
$66984.00


1754
$81588.00


1755
$74028.00


1756
$90618.00


1757
$107988.00


1758
$46668.00


1759
$93745.60


1760
$87384.00


1761
$89568.00


1762
$94584.00


1763
$98016.00


1764
$96918.00


1765
$101442.00


1766
$58908.00


1767
$86580.00


1768
$84450.00


1769
$84450.00


1770
$111474.00


1771
$98016.00


1772
$74028.00


1773
$90618.00


1774
$116784.00


1775
$111474.00


1776
$74028.00


1777
$73964.80


1778
$100884.00


1779
$68028.00


1780
$81588.00


1781
$89568.00


1782
$94328.00


1783
$111474.00


1784
$94328.00


1785
$121464.00


1786
$99672.00


1787
$90618.00


1788
$73964.80


1789
$87384.00


1790
$117894.00


1791
$81536.00


1792
$18699.20


1793
$87384.00


1794
$20051.20


1795
$90618.00


1796
$88410.00


1797
$74676.00


1798
$113598.00


1799
$88410.00


1800
$111474.00


1801
$95088.00


1802
$93240.00


1803
$94584.00


1804
$87384.00


1805
$118248.00


1806
$84450.00


1807
$64428.00


1808
$87384.00


1809
$81588.00


1810
$99552.00


1811
$84450.00


1812
$61944.00


1813
$84450.00


1814
$48240.00


1815
$100248.00


1816
$89544.00


1817
$41849.60


1818
$33180.00


1819
$17846.40


1820
$20051.20


1821
$87384.00


1822
$84450.00


1823
$51516.00


1824
$48924.00


1825
$73840.00


1826
$118872.00


1827
$2756.00


1828
$22568.00


1829
$87576.00


1830
$47528.00


1831
$55920.00


1832
$64644.00


1833
$93240.00


1834
$93840.00


1835
$81536.00


1836
$58536.00


1837
$79596.00


1838
$81536.00


1839
$61488.00


1840
$98016.00


1841
$87384.00


1842
$72862.40


1843
$84450.00


1844
$90618.00


1845
$90618.00


1846
$90618.00


1847
$68028.00


1848
$20051.20


1849
$82560.00


1850
$90618.00


1851
$87384.00


1852
$87384.00


1853
$64992.00


1854
$90918.00


1855
$84450.00


1856
$90918.00


1857
$95178.00


1858
$94530.00


1859
$56544.00


1860
$2756.00


1861
$81588.00


1862
$87384.00


1863
$74676.00


1864
$46860.00


1865
$17024.80


1866
$93600.00


1867
$104628.00


1868
$84450.00


1869
$79596.00


1870
$81588.00


1871
$84450.00


1872
$84450.00


1873
$84450.00


1874
$90618.00


1875
$81536.00


1876
$89676.00


1877
$70380.00


1878
$73840.00


1879
$72862.40


1880
$25334.40


1881
$63528.00


1882
$98280.00


1883
$81536.00


1884
$89676.00


1885
$135936.00


1886
$72862.40


1887
$84450.00


1888
$66606.00


1889
$2756.00


1890
$71292.00


1891
$91476.00


1892
$104628.00


1893
$91362.00


1894
$65592.00


1895
$94328.00


1896
$87384.00


1897
$70560.00


1898
$120444.00


1899
$72862.40


1900
$118248.00


1901
$87384.00


1902
$83340.00


1903
$74676.00


1904
$56544.00


1905
$59376.00


1906
$72492.00


1907
$81588.00


1908
$104628.00


1909
$66606.00


1910
$82044.00


1911
$84450.00


1912
$18699.20


1913
$93600.00


1914
$104628.00


1915
$84450.00


1916
$98280.00


1917
$46668.00


1918
$87384.00


1919
$73840.00


1920
$87408.00


1921
$98616.00


1922
$87384.00


1923
$74676.00


1924
$75240.00


1925
$20051.20


1926
$92682.00


1927
$100320.00


1928
$101628.84


1929
$46656.00


1930
$87384.00


1931
$81536.00


1932
$81588.00


1933
$53376.00


1934
$91752.00


1935
$58281.60


1936
$66606.00


1937
$87384.00


1938
$110088.00


1939
$2756.00


1940
$90618.00


1941
$81588.00


1942
$94584.00


1943
$81588.00


1944
$93600.00


1945
$70896.00


1946
$74304.00


1947
$103032.00


1948
$84450.00


1949
$87384.00


1950
$14684.80


1951
$110970.00


1952
$111474.00


1953
$91362.00


1954
$54654.00


1955
$92784.00


1956
$89568.00


1957
$90618.00


1958
$78204.00


1959
$65472.00


1960
$81588.00


1961
$89568.00


1962
$87384.00


1963
$94824.00


1964
$84450.00


1965
$16816.80


1966
$92682.00


1967
$131688.00


1968
$154992.00


1969
$50004.00


1970
$84450.00


1971
$89880.00


1972
$66606.00


1973
$74028.00


1974
$136836.00


1975
$95742.36


1976
$84450.00


1977
$90618.00


1978
$49512.00


1979
$93240.00


1980
$43201.60


1981
$87384.00


1982
$95178.00


1983
$107988.00


1984
$90618.00


1985
$98016.00


1986
$107988.00


1987
$90618.00


1988
$84450.00


1989
$86538.00


1990
$84450.00


1991
$21672.00


1992
$94584.00


1993
$70380.00


1994
$73840.00


1995
$98016.00


1996
$87384.00


1997
$69240.00


1998
$17586.40


1999
$71292.00


2000
$90618.00


2001
$93240.00


2002
$70380.00


2003
$93240.00


2004
$81588.00


2005
$89676.00


2006
$13520.00


2007
$93240.00


2008
$84450.00


2009
$125190.00


2010
$94530.00


2011
$22557.60


2012
$74028.00


2013
$132780.00


2014
$59184.00


2015
$54654.00


2016
$93600.00


2017
$72862.40


2018
$90618.00


2019
$84450.00


2020
$87384.00


2021
$110088.00


2022
$93600.00


2023
$72862.40


2024
$81536.00


2025
$44824.00


2026
$72862.40


2027
$20051.20


2028
$98016.00


2029
$98675.20


2030
$87384.00


2031
$104628.00


2032
$93240.00


2033
$104628.00


2034
$97760.00


2035
$100320.00


2036
$90618.00


2037
$162684.00


2038
$125190.00


2039
$81588.00


2040
$90618.00


2041
$81536.00


2042
$70380.00


2043
$81588.00


2044
$17846.40


2045
$56544.00


2046
$20020.00


2047
$66606.00


2048
$72862.40


2049
$87384.00


2050
$93240.00


2051
$87384.00


2052
$80880.00


2053
$64992.00


2054
$53172.00


2055
$129747.80


2056
$91476.00


2057
$66606.00


2058
$125190.00


2059
$90744.00


2060
$87384.00


2061
$19572.80


2062
$94530.00


2063
$46668.00


2064
$81536.00


2065
$98799.96


2066
$74028.00


2067
$86538.00


2068
$65472.00


2069
$81588.00


2070
$90618.00


2071
$84450.00


2072
$121464.00


2073
$93600.00


2074
$102702.00


2075
$75961.60


2076
$51516.00


2077
$87384.00


2078
$87324.00


2079
$121752.00


2080
$84450.00


2081
$98675.20


2082
$104628.00


2083
$93240.00


2084
$100248.00


2085
$66606.00


2086
$89568.00


2087
$89568.00


2088
$93240.00


2089
$92248.00


2090
$87384.00


2091
$54654.00


2092
$81536.00


2093
$104628.00


2094
$121464.00


2095
$52000.08


2096
$62004.00


2097
$93240.00


2098
$117894.00


2099
$20051.20


2100
$90918.00


2101
$73840.00


2102
$145116.00


2103
$90618.00


2104
$100320.00


2105
$89568.00


2106
$73840.00


2107
$88656.00


2108
$65582.40


2109
$73840.00


2110
$75240.00


2111
$81588.00


2112
$78768.00


2113
$92682.00


2114
$70380.00


2115
$90618.00


2116
$56544.00


2117
$17846.40


2118
$2756.00


2119
$92040.00


2120
$69240.00


2121
$81536.00


2122
$14684.80


2123
$72862.40


2124
$100048.00


2125
$73840.00


2126
$81948.00


2127
$20051.20


2128
$107988.00


2129
$87384.00


2130
$81588.00


2131
$90618.00


2132
$86538.00


2133
$66606.00


2134
$87384.00


2135
$84450.00


2136
$74028.00


2137
$100344.00


2138
$69324.00


2139
$109200.00


2140
$74676.00


2141
$94530.00


2142
$99552.00


2143
$14060.80


2144
$14060.80


2145
$43430.40


2146
$90618.00


2147
$74676.00


2148
$81588.00


2149
$81536.00


2150
$90618.00


2151
$104628.00


2152
$72862.40


2153
$77670.00


2154
$90618.00


2155
$87384.00


2156
$94530.00


2157
$48924.00


2158
$2756.00


2159
$98280.00


2160
$93240.00


2161
$46668.00


2162
$84450.00


2163
$88596.00


2164
$2756.00


2165
$86538.00


2166
$58284.00


2167
$92682.00


2168
$81536.00


2169
$87384.00


2170
$68028.00


2171
$94584.00


2172
$67452.00


2173
$20051.20


2174
$90618.00


2175
$87384.00


2176
$89676.00


2177
$92682.00


2178
$20051.20


2179
$74028.00


2180
$46668.00


2181
$100048.00


2182
$86538.00


2183
$98280.00


2184
$74028.00


2185
$89568.00


2186
$84450.00


2187
$97812.00


2188
$72862.40


2189
$14060.80


2190
$81588.00


2191
$81588.00


2192
$13520.00


2193
$92248.00


2194
$84450.00


2195
$90667.20


2196
$94584.00


2197
$79596.00


2198
$16816.80


2199
$111192.00


2200
$87384.00


2201
$107988.00


2202
$81588.00


2203
$81588.00


2204
$87384.00


2205
$71292.00


2206
$22568.00


2207
$64524.00


2208
$46668.00


2209
$90618.00


2210
$18699.20


2211
$72862.40


2212
$14060.80


2213
$74676.00


2214
$67766.40


2215
$43222.40


2216
$148284.00


2217
$2756.00


2218
$81536.00


2219
$89676.00


2220
$97812.00


2221
$13520.00


2222
$89676.00


2223
$84450.00


2224
$87384.00


2225
$22568.00


2226
$84450.00


2227
$104628.00


2228
$90618.00


2229
$88596.00


2230
$81588.00


2231
$100884.00


2232
$93745.60


2233
$118248.00


2234
$72862.40


2235
$90618.00


2236
$72862.40


2237
$112008.00


2238
$145116.00


2239
$110970.00


2240
$99228.00


2241
$77670.00


2242
$99816.00


2243
$44352.00


2244
$84450.00


2245
$72862.40


2246
$73840.00


2247
$74028.00


2248
$83340.00


2249
$125190.00


2250
$74676.00


2251
$81588.00


2252
$74028.00


2253
$48648.00


2254
$20051.20


2255
$90618.00


2256
$89568.00


2257
$72862.40


2258
$98016.00


2259
$81536.00


2260
$89544.00


2261
$49512.00


2262
$90918.00


2263
$104628.00


2264
$43201.60


2265
$84450.00


2266
$84450.00


2267
$87384.00


2268
$107988.00


2269
$111474.00


2270
$87384.00


2271
$87384.00


2272
$93240.00


2273
$104628.00


2274
$111474.00


2275
$72862.40


2276
$84450.00


2277
$74028.00


2278
$84450.00


2279
$84450.00


2280
$81588.00


2281
$72862.40


2282
$66768.00


2283
$162684.00


2284
$12844.00


2285
$101442.00


2286
$67766.40


2287
$66606.00


2288
$87384.00


2289
$92700.00


2290
$87384.00


2291
$145116.00


2292
$90618.00


2293
$81588.00


2294
$84450.00


2295
$81588.00


2296
$70380.00


2297
$18720.00


2298
$106980.00


2299
$74028.00


2300
$51516.00


2301
$19572.80


2302
$74676.00


2303
$73840.00


2304
$51516.00


2305
$94584.00


2306
$17846.40


2307
$111474.00


2308
$90618.00


2309
$90618.00


2310
$20498.40


2311
$100344.00


2312
$111474.00


2313
$53664.00


2314
$81588.00


2315
$86538.00


2316
$62220.00


2317
$41849.60


2318
$97760.00


2319
$84924.00


2320
$110970.00


2321
$90618.00


2322
$81536.00


2323
$100048.00


2324
$62004.00


2325
$87384.00


2326
$18720.00


2327
$93240.00


2328
$111474.00


2329
$72862.40


2330
$74131.20


2331
$89544.00


2332
$46668.00


2333
$90744.00


2334
$87384.00


2335
$87384.00


2336
$84450.00


2337
$66606.00


2338
$90618.00


2339
$51216.00


2340
$126301.56


2341
$102084.00


2342
$86538.00


2343
$84450.00


2344
$94584.00


2345
$170112.00


2346
$74028.00


2347
$94328.00


2348
$106288.00


2349
$84450.00


2350
$68028.00


2351
$100884.00


2352
$70380.00


2353
$111474.00


2354
$87384.00


2355
$37248.00


2356
$84450.00


2357
$90618.00


2358
$110970.00


2359
$66606.00


2360
$22557.60


2361
$82044.00


2362
$87384.00


2363
$93246.40


2364
$81588.00


2365
$74028.00


2366
$90618.00


2367
$72862.40


2368
$87384.00


2369
$87384.00


2370
$98016.00


2371
$91704.00


2372
$70380.00


2373
$95178.00


2374
$89568.00


2375
$87384.00


2376
$84450.00


2377
$87384.00


2378
$70380.00


2379
$84450.00


2380
$84450.00


2381
$92682.00


2382
$84450.00


2383
$59184.00


2384
$72862.40


2385
$86538.00


2386
$56544.00


2387
$90618.00


2388
$76428.00


2389
$72862.40


2390
$111474.00


2391
$46668.00


2392
$93240.00


2393
$87384.00


2394
$106836.00


2395
$62580.00


2396
$91476.00


2397
$88410.00


2398
$90918.00


2399
$15288.00


2400
$78948.00


2401
$87384.00


2402
$83340.00


2403
$51516.00


2404
$87384.00


2405
$84450.00


2406
$117264.00


2407
$65894.40


2408
$136836.00


2409
$25898.60


2410
$92682.00


2411
$65172.00


2412
$95178.00


2413
$86538.00


2414
$72862.40


2415
$72862.40


2416
$81536.00


2417
$104520.00


2418
$93600.00


2419
$78264.00


2420
$87384.00


2421
$51516.00


2422
$84450.00


2423
$78204.00


2424
$56544.00


2425
$62004.00


2426
$98016.00


2427
$44254.08


2428
$98616.00


2429
$81536.00


2430
$87384.00


2431
$93600.00


2432
$94584.00


2433
$145116.00


2434
$81588.00


2435
$90618.00


2436
$81536.00


2437
$49512.00


2438
$104628.00


2439
$87384.00


2440
$20051.20


2441
$68568.00


2442
$87384.00


2443
$111474.00


2444
$84450.00


2445
$93246.40


2446
$84450.00


2447
$117948.00


2448
$91476.00


2449
$53904.00


2450
$62004.00


2451
$14060.80


2452
$62004.00


2453
$87384.00


2454
$18699.20


2455
$66984.00


2456
$65582.40


2457
$81536.00


2458
$72862.40


2459
$98016.00


2460
$66606.00


2461
$84450.00


2462
$104628.00


2463
$89544.00


2464
$155040.00


2465
$111474.00


2466
$98712.00


2467
$68568.00


2468
$89676.00


2469
$73840.00


2470
$90618.00


2471
$87384.00


2472
$91476.00


2473
$87384.00


2474
$90618.00


2475
$100048.00


2476
$68028.00


2477
$81588.00


2478
$94328.00


2479
$90618.00


2480
$69825.60


2481
$74028.00


2482
$100884.00


2483
$57084.00


2484
$20498.40


2485
$10400.00


2486
$70380.00


2487
$94584.00


2488
$110970.00


2489
$100048.00


2490
$77670.00


2491
$70380.00


2492
$20051.20


2493
$95820.00


2494
$86538.00


2495
$98016.00


2496
$84450.00


2497
$74028.00


2498
$69825.60


2499
$93240.00


2500
$74028.00


2501
$20498.40


2502
$104436.84


2503
$66606.00


2504
$84450.00


2505
$94584.00


2506
$86538.00


2507
$92682.00


2508
$90618.00


2509
$86538.00


2510
$93745.60


2511
$87384.00


2512
$72862.40


2513
$74028.00


2514
$90618.00


2515
$56544.00


2516
$2756.00


2517
$18699.20


2518
$87384.00


2519
$75384.00


2520
$14570.40


2521
$46656.00


2522
$81588.00


2523
$86538.00


2524
$94584.00


2525
$61728.00


2526
$119208.00


2527
$98675.20


2528
$100344.00


2529
$16816.80


2530
$118248.00


2531
$93240.00


2532
$118414.44


2533
$84450.00


2534
$90618.00


2535
$53172.00


2536
$84450.00


2537
$110970.00


2538
$93600.00


2539
$90540.00


2540
$90618.00


2541
$106836.00


2542
$82560.00


2543
$20051.20


2544
$25898.60


2545
$90618.00


2546
$46668.00


2547
$104916.00


2548
$70380.00


2549
$87384.00


2550
$81588.00


2551
$73840.00


2552
$48924.00


2553
$98799.96


2554
$25898.60


2555
$111474.00


2556
$73840.00


2557
$20051.20


2558
$51516.00


2559
$87384.00


2560
$84450.00


2561
$94584.00


2562
$40812.00


2563
$94328.00


2564
$94884.00


2565
$89676.00


2566
$84450.00


2567
$84450.00


2568
$89880.00


2569
$106020.00


2570
$90618.00


2571
$84450.00


2572
$56544.00


2573
$20051.20


2574
$73840.00


2575
$81588.00


2576
$98016.00


2577
$84450.00


2578
$100048.00


2579
$93745.60


2580
$84450.00


2581
$73840.00


2582
$58284.00


2583
$104748.00


2584
$44824.00


2585
$92682.00


2586
$82044.00


2587
$78204.00


2588
$54360.00


2589
$33972.00


2590
$73840.00


2591
$22568.00


2592
$81536.00


2593
$111474.00


2594
$86538.00


2595
$52356.00


2596
$68028.00


2597
$51216.00


2598
$58281.60


2599
$73840.00


2600
$46668.00


2601
$81948.00


2602
$84450.00


2603
$84888.00


2604
$87384.00


2605
$16816.80


2606
$87384.00


2607
$54348.00


2608
$89568.00


2609
$110970.00


2610
$34008.00


2611
$81948.00


2612
$76428.00


2613
$81588.00


2614
$20051.20


2615
$72862.40


2616
$20051.20


2617
$89568.00


2618
$59184.00


2619
$64296.00


2620
$84450.00


2621
$81588.00


2622
$86538.00


2623
$87384.00


2624
$99840.00


2625
$111474.00


2626
$90618.00


2627
$46668.00


2628
$66606.00


2629
$81588.00


2630
$90618.00


2631
$66606.00


2632
$104628.00


2633
$66606.00


2634
$94328.00


2635
$91476.00


2636
$81536.00


2637
$67766.40


2638
$73840.00


2639
$87384.00


2640
$84450.00


2641
$84450.00


2642
$145116.00


2643
$93600.00


2644
$72862.40


2645
$93240.00


2646
$84450.00


2647
$73840.00


2648
$89340.00


2649
$20051.20


2650
$81536.00


2651
$84450.00


2652
$66606.00


2653
$92248.00


2654
$81588.00


2655
$100320.00


2656
$87384.00


2657
$66606.00


2658
$69324.00


2659
$16395.60


2660
$20051.20


2661
$58572.00


2662
$90618.00


2663
$93240.00


2664
$73840.00


2665
$100344.00


2666
$87384.00


2667
$51012.00


2668
$100884.00


2669
$78204.00


2670
$72862.40


2671
$98016.00


2672
$96096.00


2673
$73840.00


2674
$20498.40


2675
$81588.00


2676
$64992.00


2677
$83340.00


2678
$97812.00


2679
$100048.00


2680
$90618.00


2681
$90618.00


2682
$2756.00


2683
$87384.00


2684
$50784.00


2685
$9620.00


2686
$20051.20


2687
$57324.00


2688
$74028.00


2689
$115356.00


2690
$71292.00


2691
$51516.00


2692
$73840.00


2693
$121464.00


2694
$49140.00


2695
$87384.00


2696
$100884.00


2697
$71820.00


2698
$62496.00


2699
$20498.40


2700
$48924.00


2701
$84450.00


2702
$82044.00


2703
$95088.00


2704
$98799.96


2705
$87384.00


2706
$86538.00


2707
$132780.00


2708
$81588.00


2709
$98675.20


2710
$98799.96


2711
$106980.00


2712
$16395.60


2713
$62496.00


2714
$73840.00


2715
$18699.20


2716
$90618.00


2717
$84450.00


2718
$87384.00


2719
$20051.20


2720
$20051.20


2721
$91704.00


2722
$90618.00


2723
$81588.00


2724
$33972.00


2725
$94584.00


2726
$87384.00


2727
$44574.40


2728
$74028.00


2729
$84450.00


2730
$67452.00


2731
$110970.00


2732
$89676.00


2733
$25334.40


2734
$73840.00


2735
$72862.40


2736
$46668.00


2737
$111474.00


2738
$90618.00


2739
$87384.00


2740
$74028.00


2741
$100884.00


2742
$84450.00


2743
$94328.00


2744
$81536.00


2745
$53172.00


2746
$111474.00


2747
$87384.00


2748
$107988.00


2749
$46668.00


2750
$107988.00


2751
$98016.00


2752
$87384.00


2753
$72862.40


2754
$65172.00


2755
$84450.00


2756
$90618.00


2757
$90288.00


2758
$60540.00


2759
$18699.20


2760
$89568.00


2761
$100048.00


2762
$66984.00


2763
$72862.40


2764
$93240.00


2765
$84450.00


2766
$84450.00


2767
$93240.00


2768
$74028.00


2769
$98016.00


2770
$72862.40


2771
$72862.40


2772
$25334.40


2773
$90618.00


2774
$20051.20


2775
$18699.20


2776
$86538.00


2777
$77364.00


2778
$87838.40


2779
$74028.00


2780
$86538.00


2781
$51216.00


2782
$68028.00


2783
$72862.40


2784
$100320.00


2785
$95178.00


2786
$90228.00


2787
$98016.00


2788
$87384.00


2789
$16317.60


2790
$25334.40


2791
$81588.00


2792
$87384.00


2793
$98799.96


2794
$107988.00


2795
$90918.00


2796
$48240.00


2797
$81536.00


2798
$110970.00


2799
$90744.00


2800
$145116.00


2801
$100470.00


2802
$98280.00


2803
$121464.00


2804
$48240.00


2805
$84450.00


2806
$87384.00


2807
$136836.00


2808
$136836.00


2809
$73840.00


2810
$25898.60


2811
$41849.60


2812
$94584.00


2813
$100320.00


2814
$94530.00


2815
$111474.00


2816
$84450.00


2817
$136170.00


2818
$87384.00


2819
$84450.00


2820
$139488.00



In [27]:
chicago.head()
chicago.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32063 entries, 0 to 32062
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  object
 3   Employee Annual Salary  32062 non-null  object
dtypes: object(4)
memory usage: 1002.1+ KB

Filtering data

In [37]:
chicago.loc[chicago["Department"] == "WATER"]
# its a string column so doesnt work Employee Annual Salary
# chicago.loc[chicago["Employee Annual Salary"] > 1000000]

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,WATER,$84450.00
2,"AARON, KARINA",POLICE OFFICER,WATER,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,WATER,$89880.00

In [44]:
chicago.loc[chicago["Department"] == "OECM", ["Name", "Department"]]
chicago[chicago["Department"] == "WATER"][["Name", "Department"]]
chicago[(chicago["Department"] == "WATER") & (chicago["Position Title"] == "POLICE OFFICER")]

                Name  Position Title Department Employee Annual Salary
1  AARON,  JEFFERY M  POLICE OFFICER      WATER              $84450.00
2     AARON,  KARINA  POLICE OFFICER      WATER              $84450.00

In [12]:
chicago[chicago["Position Title"].str.contains("WATER", na=False)]
# na=False, helps to tell it to ignore null values, it kept throing an error due to them

chicago[chicago["Position Title"].str.contains("FOREMAN | CHEMIST", na=False)]

,Name,Position Title,Department,Employee Annual Salary
113,"ADAM, RICHARD",FOREMAN OF MOTOR TRUCK DRIVERS,STREETS & SAN,$76876.80
481,"ALLEN, TERRY L",FOREMAN OF CONSTRUCTION LABORERS,TRANSPORTN,$83824.00
554,"ALUISE, VINCENT G",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
658,"AMRAEN, DAVID J",FOREMAN OF HOISTING ENGINEERS,GENERAL SERVICES,$108368.00
671,"ANDER, PERRY A",WATER CHEMIST II,WATER MGMNT,$82044.00
...,...,...,...,...
31641,"YATES, THOMAS E",FOREMAN OF CONSTRUCTION LABORERS,TRANSPORTN,$83824.00
31900,"ZECEVICH, DRAGAN",FOREMAN OF ELECTRICAL MECHANICS,WATER MGMNT,$99840.00
31910,"ZELAYA, MANUEL E",FOREMAN OF PAINTERS,AVIATION,$100734.40
31937,"ZHANG, JACKIE L",FOREMAN OF CEMENT FINISHERS,TRANSPORTN,$95160.00
31955,"ZIELINSKI, ROBERT",FOREMAN OF CEMENT FINISHERS,TRANSPORTN,$95160.00

In [28]:
chicago[chicago["Department"].isin(["WATER MGMNT", "CHEMIST"])]
# you have to put the whole value, not same as contains

chicago[chicago["Department"].isin(["WATER MGMNT", "CHEMIST"]) & (chicago["Position Title"].str.contains("WATER", na=False))]

chicago[chicago["Department"].isin(["WATER MGMNT", "CHEMIST"]) & (chicago["Position Title"].str.startswith("WATER", na=False))]

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
671,"ANDER, PERRY A",WATER CHEMIST II,WATER MGMNT,$82044.00
1054,"ASHLEY, KARMA T",WATER CHEMIST II,WATER MGMNT,$82044.00
1079,"ATKINS, JOANNA M",WATER CHEMIST II,WATER MGMNT,$82044.00
1181,"AZEEM, MOHAMMED A",WATER CHEMIST II,WATER MGMNT,$53172.00
...,...,...,...,...
28574,"THREATT, DENISE R",WATER QUALITY INSPECTOR,WATER MGMNT,$62004.00
28602,"TIGNOR, DARRYL B",WATER RATE TAKER,WATER MGMNT,$78948.00
28955,"TRAVIS COOK, LESLIE R",WATER RATE TAKER,WATER MGMNT,$78948.00
29584,"VELAZQUEZ, JOHN",WATER RATE TAKER,WATER MGMNT,$78948.00
30239,"WASHINGTON, JOSEPH",WATER CHEMIST III,WATER MGMNT,$89676.00

In [ ]:
CAN use a query funciton

In [34]:
# chicago.query('Department == "WATER MGMNT" and Position Title == "WATER RATE TAKER"')
# this should ave worked but the position title has a space, use back ticks if has space
chicago.query('Department == "WATER MGMNT" and `Position Title` == "WATER RATE TAKER"')

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
2400,"BOLTON, BRIAN E",WATER RATE TAKER,WATER MGMNT,$78948.00
3143,"BROWN, SHARON L",WATER RATE TAKER,WATER MGMNT,$82728.00
3456,"BURT, CARL S",WATER RATE TAKER,WATER MGMNT,$90744.00
3626,"CAGE, OPHELIA",WATER RATE TAKER,WATER MGMNT,$90744.00
6954,"DIAZ, OSCAR A",WATER RATE TAKER,WATER MGMNT,$90744.00
7641,"DURANT, PATRICIA B",WATER RATE TAKER,WATER MGMNT,$90744.00
8092,"ESPINOSA, RODOLFO",WATER RATE TAKER,WATER MGMNT,$78948.00
11857,"HEDRICK, LEE A",WATER RATE TAKER,WATER MGMNT,$78948.00
13729,"JOHNSON, CURTIS V",WATER RATE TAKER,WATER MGMNT,$75384.00
14771,"KHAN, INAYAT U",WATER RATE TAKER,WATER MGMNT,$90744.00
15215,"KORDOWSKI, ANTHONY",WATER RATE TAKER,WATER MGMNT,$86580.00
16189,"LEWIS, BYRON",WATER RATE TAKER,WATER MGMNT,$90744.00
24003,"RIOS, FRANCISCO",WATER RATE TAKER,WATER MGMNT,$78948.00
24501,"RODRIGUEZ, MARCO A",WATER RATE TAKER,WATER MGMNT,$90744.00
26519,"SIMS, DEMETRIUS",WATER RATE TAKER,WATER MGMNT,$90744.00
26625,"SKOWRON, JOHN",WATER RATE TAKER,WATER MGMNT,$90744.00
26871,"SMITH, NANCY A",WATER RATE TAKER,WATER MGMNT,$90744.00
28185,"TATE, GARY",WATER RATE TAKER,WATER MGMNT,$82728.00
28443,"THOMAS, HOWARD",WATER RATE TAKER,WATER MGMNT,$78948.00
28602,"TIGNOR, DARRYL B",WATER RATE TAKER,WATER MGMNT,$78948.00
28955,"TRAVIS COOK, LESLIE R",WATER RATE TAKER,WATER MGMNT,$78948.00
29584,"VELAZQUEZ, JOHN",WATER RATE TAKER,WATER MGMNT,$78948.00

In [ ]:
Add or remove columns

In [37]:
chicago['people'] = "government"
chicago.head(3)

,Name,Position Title,Department,Employee Annual Salary,people
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,government
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,government
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,government

In [43]:
chicago.drop(columns='people' , inplace=True)
chicago.head(3)

                Name    Position Title   Department Employee Annual Salary
0    AARON,  ELVIA J  WATER RATE TAKER  WATER MGMNT              $90744.00
1  AARON,  JEFFERY M    POLICE OFFICER       POLICE              $84450.00
2     AARON,  KARINA    POLICE OFFICER       POLICE              $84450.00

In [32]:
# to copy a df into another variable use the .copy()
chicago_new = chicago.copy()

In [33]:
chicago_new['first_name'] = chicago_new['Name'].str.split(', ').str[1]
chicago_new['last_name'] = chicago_new['Name'].str.split(', ').str[0]

In [34]:
chicago_new.drop(columns='last_name', inplace = True)
chicago_new.head(3)

,Name,Position Title,Department,Employee Annual Salary,first_name
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,ELVIA J
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,JEFFERY M
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,KARINA

In [35]:
# on my new copied df i am adding a new column
chicago_new['sal_name'] = chicago_new['first_name'] + ' = ' + chicago_new['Department']

In [36]:
chicago_new.head()

,Name,Position Title,Department,Employee Annual Salary,first_name,sal_name
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,ELVIA J,ELVIA J = WATER MGMNT
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,JEFFERY M,JEFFERY M = POLICE
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,KARINA,KARINA = POLICE
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,KIMBERLEI R,KIMBERLEI R = GENERAL SERVICES
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,VICENTE M,VICENTE M = WATER MGMNT

In [37]:
chicago_new.rename(columns = {'sal_name' : 'dept_name'}, inplace = True)

In [38]:
chicago_new.head()

,Name,Position Title,Department,Employee Annual Salary,first_name,dept_name
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,ELVIA J,ELVIA J = WATER MGMNT
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,JEFFERY M,JEFFERY M = POLICE
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,KARINA,KARINA = POLICE
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,KIMBERLEI R,KIMBERLEI R = GENERAL SERVICES
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,VICENTE M,VICENTE M = WATER MGMNT

In [39]:
# chicago_new['Employee Annual Salary'] = pd.to_numeric chicago_new['Employee Annual Salary'] ['']

In [40]:
chicago_new['Annual Salary'] = pd.to_numeric(chicago_new['Employee Annual Salary'].str.split('$').str[1])

In [41]:
chicago_new.head(3)

,Name,Position Title,Department,Employee Annual Salary,first_name,dept_name,Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,ELVIA J,ELVIA J = WATER MGMNT,90744.0
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,JEFFERY M,JEFFERY M = POLICE,84450.0
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,KARINA,KARINA = POLICE,84450.0

In [14]:
chicago_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32063 entries, 0 to 32062
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  object
 3   Employee Annual Salary  32062 non-null  object
 4   first_name              32062 non-null  object
 5   dept_name               32062 non-null  object
 6   Annual Salary           32062 non-null  float64
dtypes: float64(1), object(6)
memory usage: 1.7+ MB

In [42]:
chicago_new.sort_values(by = 'Annual Salary', ascending = False)

,Name,Position Title,Department,Employee Annual Salary,first_name,dept_name,Annual Salary
8184,"EVANS, GINGER S",COMMISSIONER OF AVIATION,AVIATION,$300000.00,GINGER S,GINGER S = AVIATION,300000.00
7954,"EMANUEL, RAHM",MAYOR,MAYOR'S OFFICE,$216210.00,RAHM,RAHM = MAYOR'S OFFICE,216210.00
25532,"SANTIAGO, JOSE A",FIRE COMMISSIONER,FIRE,$202728.00,JOSE A,JOSE A = FIRE,202728.00
8924,"FORD II, RICHARD C",FIRST DEPUTY FIRE COMMISSIONER,FIRE,$197736.00,RICHARD C,RICHARD C = FIRE,197736.00
8042,"ESCALANTE, JOHN J",FIRST DEPUTY SUPERINTENDENT,POLICE,$197724.00,JOHN J,JOHN J = POLICE,197724.00
...,...,...,...,...,...,...,...
4587,"CHENG, MEE OI",FOSTER GRANDPARENT,FAMILY & SUPPORT,$2756.00,MEE OI,MEE OI = FAMILY & SUPPORT,2756.00
27,"ABDULWAHAB, ABUUBAIDA",FOSTER GRANDPARENT,FAMILY & SUPPORT,$2756.00,ABUUBAIDA,ABUUBAIDA = FAMILY & SUPPORT,2756.00
3146,"BROWN-SIMS, BARBARA A",FOSTER GRANDPARENT,FAMILY & SUPPORT,$2756.00,BARBARA A,BARBARA A = FAMILY & SUPPORT,2756.00
15102,"KOCH, STEVEN",ADMINISTRATIVE SECRETARY,MAYOR'S OFFICE,$0.96,STEVEN,STEVEN = MAYOR'S OFFICE,0.96
32062,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
chicago_new.columns

Index(['Name', 'Position Title', 'Department', 'Employee Annual Salary',
       'first_name', 'dept_name', 'Annual Salary'],
      dtype='object')

In [47]:
chicago_police = chicago_new[(chicago_new["Department"] == "POLICE") & (chicago["Position Title"] == "POLICE OFFICER")]

In [55]:
chicago_police = chicago_police[['Name', 'dept_name', 'Annual Salary']]

In [56]:
chicago_police.head(3)

                 Name            dept_name  Annual Salary
1   AARON,  JEFFERY M   JEFFERY M = POLICE        84450.0
2      AARON,  KARINA      KARINA = POLICE        84450.0
11   ABBATE,  TERRY M     TERRY M = POLICE        90618.0

In [57]:
combined_df = pd.merge(chicago_new, chicago_police, on='Name', how = 'inner' )

In [58]:
combined_df.head()

,Name,Position Title,Department,Employee Annual Salary,first_name,dept_name_x,Annual Salary_x,dept_name_y,Annual Salary_y
0,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,JEFFERY M,JEFFERY M = POLICE,84450.0,JEFFERY M = POLICE,84450.0
1,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,KARINA,KARINA = POLICE,84450.0,KARINA = POLICE,84450.0
2,"ABBATE, TERRY M",POLICE OFFICER,POLICE,$90618.00,TERRY M,TERRY M = POLICE,90618.0,TERRY M = POLICE,90618.0
3,"ABDALLAH, ZAID",POLICE OFFICER,POLICE,$74028.00,ZAID,ZAID = POLICE,74028.0,ZAID = POLICE,74028.0
4,"ABDELHADI, ABDALMAHD",POLICE OFFICER,POLICE,$81588.00,ABDALMAHD,ABDALMAHD = POLICE,81588.0,ABDALMAHD = POLICE,81588.0

In [60]:
chicago_police.head()

                     Name            dept_name  Annual Salary
1       AARON,  JEFFERY M   JEFFERY M = POLICE        84450.0
2          AARON,  KARINA      KARINA = POLICE        84450.0
11       ABBATE,  TERRY M     TERRY M = POLICE        90618.0
15        ABDALLAH,  ZAID        ZAID = POLICE        74028.0
16  ABDELHADI,  ABDALMAHD   ABDALMAHD = POLICE        81588.0

In [68]:
# chicago_new.isna().sum()
# chicago_new.interpolate() #most times better for timeseries or temperature data
# chicago_new.fillna(0).interpolate() #fill first with 0 then interpolate anythting left over
chicago_new['Annual Salary'].fillna(chicago_new['Annual Salary'].median())
chicago_new['Department'].fillna('NOT SPECIFIED')
# chicago_new.ffill() #copies the value from the row above
# chicago_new.fillna('NOT SPECIFIED').interpolate() #fill first with 0 then interpolate anythting left over

,Name,Position Title,Department,Employee Annual Salary,first_name,dept_name,Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,ELVIA J,ELVIA J = WATER MGMNT,90744.0
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,JEFFERY M,JEFFERY M = POLICE,84450.0
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,KARINA,KARINA = POLICE,84450.0
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,KIMBERLEI R,KIMBERLEI R = GENERAL SERVICES,89880.0
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,VICENTE M,VICENTE M = WATER MGMNT,106836.0
...,...,...,...,...,...,...,...
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00,PETER J,PETER J = POLICE,87384.0
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00,MARK E,MARK E = POLICE,84450.0
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00,CARLO E,CARLO E = POLICE,87384.0
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00,DARIUSZ,DARIUSZ = DoIT,113664.0
32062,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00,DARIUSZ,DARIUSZ = DoIT,113664.0

In [74]:
# chicago_new.dropna(subset=) #i didnt understand

# Returns only the rows where 'Annual Salary' is missing
chicago_new[chicago_new['Annual Salary'].isna()]

# Returns any row that has at least one NA value, This looks across the columns (horizontally). 
# If it sees even one True, it marks that whole row as True
chicago_new[chicago_new.isna().any(axis=1)]

,Name,Position Title,Department,Employee Annual Salary,first_name,dept_name,Annual Salary
32062,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
chicago_new['Department'].value_counts()
# chicago_new[chicago_new['Department'] == 'AVIATION']['Position Title'].value_counts() #Out of the people that are i aviation, count their position title

Department
POLICE                   12618
FIRE                      4796
STREETS & SAN             2152
OEMC                      1982
WATER MGMNT               1840
AVIATION                  1521
TRANSPORTN                1073
PUBLIC LIBRARY             961
GENERAL SERVICES           930
FAMILY & SUPPORT           654
FINANCE                    577
HEALTH                     529
LAW                        414
CITY COUNCIL               396
BUILDINGS                  262
COMMUNITY DEVELOPMENT      208
BUSINESS AFFAIRS           161
BOARD OF ELECTION          117
DoIT                       102
CITY CLERK                  94
MAYOR'S OFFICE              86
PROCUREMENT                 83
IPRA                        82
CULTURAL AFFAIRS            74
HUMAN RESOURCES             70
ANIMAL CONTRL               67
INSPECTOR GEN               57
BUDGET & MGMT               39
ADMIN HEARNG                39
DISABILITIES                28
TREASURER                   22
HUMAN RELATIONS             16
BOARD OF ETHICS              9
POLICE BOARD                 2
LICENSE APPL COMM            1
Name: count, dtype: int64

In [ ]:
chicago_new['Department'].value_counts()
chicago_new[chicago_new['Position Title']

In [85]:
# chicago_new.groupby(['Department'])['Position Title'].sum()

# chicago_new.groupby(chicago_new['Annual Salary'])['Name'].count()

chicago_new.groupby(chicago_new['Annual Salary'])['Name'].count().reset_index().sort_values('Name', ascending= False)

      Annual Salary  Name
654         87384.0  2394
621         84450.0  2198
689         90618.0  1406
486         72862.4  1371
585         81588.0  1342
...             ...   ...
27          15371.2     1
28          15527.2     1
30          16078.4     1
31          16120.0     1
1121       156420.0     1

[1156 rows x 2 columns]

In [97]:
# chicago_new['Salary_rank']= chicago_new['Annual Salary'].rank()

chicago_new['Salary_rank']= chicago_new['Annual Salary'].rank(ascending = False)

In [99]:
chicago_new.sort_values(['Salary_rank'])

,Name,Position Title,Department,Employee Annual Salary,first_name,dept_name,Annual Salary,Salary_rank
8184,"EVANS, GINGER S",COMMISSIONER OF AVIATION,AVIATION,$300000.00,GINGER S,GINGER S = AVIATION,300000.00,1.0
7954,"EMANUEL, RAHM",MAYOR,MAYOR'S OFFICE,$216210.00,RAHM,RAHM = MAYOR'S OFFICE,216210.00,2.0
25532,"SANTIAGO, JOSE A",FIRE COMMISSIONER,FIRE,$202728.00,JOSE A,JOSE A = FIRE,202728.00,3.0
8924,"FORD II, RICHARD C",FIRST DEPUTY FIRE COMMISSIONER,FIRE,$197736.00,RICHARD C,RICHARD C = FIRE,197736.00,4.0
8042,"ESCALANTE, JOHN J",FIRST DEPUTY SUPERINTENDENT,POLICE,$197724.00,JOHN J,JOHN J = POLICE,197724.00,5.0
...,...,...,...,...,...,...,...,...
10148,"GLUZMAN, LEONID",SENIOR COMPANION,FAMILY & SUPPORT,$2756.00,LEONID,LEONID = FAMILY & SUPPORT,2756.00,31947.0
22659,"POLEVOY, IRINA",SENIOR COMPANION,FAMILY & SUPPORT,$2756.00,IRINA,IRINA = FAMILY & SUPPORT,2756.00,31947.0
47,"ABREU, VICTOR",SENIOR COMPANION,FAMILY & SUPPORT,$2756.00,VICTOR,VICTOR = FAMILY & SUPPORT,2756.00,31947.0
15102,"KOCH, STEVEN",ADMINISTRATIVE SECRETARY,MAYOR'S OFFICE,$0.96,STEVEN,STEVEN = MAYOR'S OFFICE,0.96,32062.0
32062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
chicago.isna().sum()

Name                      1
Position Title            1
Department                1
Employee Annual Salary    1
dtype: int64