## Pandas tutorial
Here I learn how to use pandas to perform an ETL. 

In addition, I create a function that can help perform this ETL.

In [3]:
import pandas as pd

In [4]:
file = pd.read_csv('customers.csv')
file.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [5]:
file.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [6]:
customer_info = file[[ 'Index', 'First Name', 'Last Name', 'Country','Phone 1', 'Email', 'Subscription Date']]

In [7]:
customer_info.head()

,Index,First Name,Last Name,Country,Phone 1,Email,Subscription Date
0,1,Sheryl,Baxter,Chile,229.077.5154,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,Djibouti,5153435776,vmata@colon.com,2021-04-23
2,3,Roy,Berry,Antigua and Barbuda,+1-539-402-0259,beckycarr@hogan.com,2020-03-25
3,4,Linda,Olsen,Dominican Republic,001-808-617-6467x12895,stanleyblackwell@benson.org,2020-06-02
4,5,Joanna,Bender,Slovakia (Slovak Republic),001-234-203-0635x76146,colinalvarado@miles.net,2021-04-17

In [8]:
newly_subscribed = customer_info[customer_info["Subscription Date"] > '2022-01-01']

In [9]:
newly_subscribed.head()

,Index,First Name,Last Name,Country,Phone 1,Email,Subscription Date
14,15,Faith,Lutz,Singapore,(781)861-7180x8306,cassieparrish@blevins-chapman.net,2022-01-26
15,16,Miranda,Beasley,Oman,540.085.3135x185,vduncan@parks-hardy.com,2022-04-12
17,18,Greg,Mata,Mozambique,(701)087-2415,jaredjuarez@carroll.org,2022-03-26
20,21,Maxwell,Frye,Malta,423.262.3059,fgibson@drake-webb.com,2022-01-12
25,26,Marcus,Moody,Panama,674-677-8623,donnamullins@norris-barrett.org,2022-05-24

In [10]:
newly_subscribed.count()

Index                19
First Name           19
Last Name            19
Country              19
Phone 1              19
Email                19
Subscription Date    19
dtype: int64

In [12]:
newly_subscribed.to_csv('new_subscribers_2022.csv', index = False)

Function for the ETL pipeline:

In [16]:
def extract_data(csv_file):
    file = pd.read_csv(csv_file)
    print(file.head(3))
    return "file reading successful"

In [17]:
extract_data('customers.csv')

   Index      Customer Id First Name Last Name          Company  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter  Rasmussen Group
1      2  1Ef7b82A4CAAD10    Preston    Lozano      Vega-Gentry
2      3  6F94879bDAfE5a6        Roy     Berry    Murillo-Perry

                City              Country          Phone 1  \
0       East Leonard                Chile     229.077.5154
1  East Jimmychester             Djibouti       5153435776
2      Isabelborough  Antigua and Barbuda  +1-539-402-0259

               Phone 2                     Email Subscription Date  \
0     397.884.0519x718  zunigavanessa@smith.info        2020-08-24
1     686-620-1820x944           vmata@colon.com        2021-04-23
2  (496)978-3969x58947       beckycarr@hogan.com        2020-03-25

                      Website
0  http://www.stephenson.com/
1       http://www.hobbs.com/
2    http://www.lawrence.com/

'file reading successful'

In [18]:
def transform(file):
    print("getting newly subscribed customers since 2022")
    newly_subscribed = file[file["Subscription Date"] > '2022-01-01']
    print(newly_subscribed.head(3))
    return "transformation successful"

In [19]:
transform(file)

getting newly subscribed customers since 2022
    Index      Customer Id First Name Last Name             Company  \
14     15  6fEaA1b7cab7B6C      Faith      Lutz      Carter-Hancock
15     16  8cad0b4CBceaeec    Miranda   Beasley  Singleton and Sons
17     18  F8Aa9d6DfcBeeF8       Greg      Mata       Valentine LLC

            City     Country             Phone 1                Phone 2  \
14     Burchbury   Singapore  (781)861-7180x8306           207-185-3665
15  Desireeshire        Oman    540.085.3135x185  +1-600-462-6432x21881
17   Lake Leslie  Mozambique       (701)087-2415    (195)156-1861x26241

                                Email Subscription Date  \
14  cassieparrish@blevins-chapman.net        2022-01-26
15            vduncan@parks-hardy.com        2022-04-12
17            jaredjuarez@carroll.org        2022-03-26

                     Website
14     http://stevenson.org/
15        http://acosta.org/
17  http://pitts-cherry.com/

'transformation successful'

In [24]:
def load_data(newly_subscribed):
    file_name = input("whats your output file name?: ")
    if '/' in file_name or '\\' in file_name:
        print("Invalid characters like / or \ in file_name")
    else:    
        newly_subscribed.to_csv(f'{file_name}.csv', index = False)
    return f"file successfully stored as {file_name}.csv"

In [25]:
load_data(newly_subscribed)

whats your output file name?:  none

'file successfully stored as none.csv'

In [45]:
# def get_subscribers(csv_file):
#     file = pd.read_csv(csv_file)
#     newly_subscribed = file[file["Subscription Date"] > '2022-01-01']
#     newly_subscribed.to_csv('part_one.csv', index = False)
#     print(newly_subscribed.head(2))
#     return "transformation successful"

In [ ]:
# get_subscribers('customers.csv')