## ETL tutorial
Here I learn how to use pandas to perform an ETL.

In addition, I create a function that can help perform this ETL to move excel files

In [21]:
import pandas as pd

Exploratory Data Analysis

In [3]:
medical_xl = pd.read_excel('excel_files/treatment_history.xlsx')
medical_xl.head(4)

,Patient ID,Treatment Date,Treatment Type,Outcome,Follow-up Date,Next Steps
0,c143b0f5-8f2a-43fe-9723-7229e50fba3d,2026-01-25,Radiation Therapy,Ongoing,2026-03-05,Observation
1,3b6d2104-c355-4561-8c70-b83a5a2a02a8,2026-02-11,Radiation Therapy,Failed,2026-02-26,Observation
2,549e9b21-b1ac-4ca9-85f1-b89ab5f5c4ba,2026-02-05,Targeted Therapy,Failed,2026-01-28,Radiation Therapy
3,1c0b71f4-5158-4b27-9a0a-b537c2e95b2d,2026-01-24,Surgery,Partial Response,2026-03-01,More Chemotherapy

In [3]:
medical_xl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient ID      1000 non-null   object
 1   Treatment Date  1000 non-null   datetime64[ns]
 2   Treatment Type  1000 non-null   object
 3   Outcome         1000 non-null   object
 4   Follow-up Date  1000 non-null   datetime64[ns]
 5   Next Steps      1000 non-null   object
dtypes: datetime64[ns](2), object(4)
memory usage: 47.0+ KB

In [5]:
medical_xl.shape
medical_xl.values
medical_xl.columns
medical_xl.size
medical_xl.describe

<bound method NDFrame.describe of                                Patient ID Treatment Date     Treatment Type  \
0    c143b0f5-8f2a-43fe-9723-7229e50fba3d     2026-01-25  Radiation Therapy
1    3b6d2104-c355-4561-8c70-b83a5a2a02a8     2026-02-11  Radiation Therapy
2    549e9b21-b1ac-4ca9-85f1-b89ab5f5c4ba     2026-02-05   Targeted Therapy
3    1c0b71f4-5158-4b27-9a0a-b537c2e95b2d     2026-01-24            Surgery
4    12bf96f0-60ce-450b-a794-4783b9659b73     2026-01-15      Immunotherapy
..                                    ...            ...                ...
995  601f18b4-1b02-4a1f-a0c9-3a10b2cbe8d0     2026-02-09      Immunotherapy
996  ceac0003-2c37-4ea1-8edb-1bbec648401f     2026-01-02            Surgery
997  6f21f65b-9d46-472a-a603-fa31790efeaf     2026-03-03   Targeted Therapy
998  0172d147-37eb-434d-83cf-b5514144f9c4     2026-01-08      Immunotherapy
999  8028a47d-dc0f-4629-ab13-81bcafa8f8a7     2026-01-13   Targeted Therapy

              Outcome Follow-up Date         Next Steps
0             Ongoing     2026-03-05        Observation
1              Failed     2026-02-26        Observation
2              Failed     2026-01-28  Radiation Therapy
3    Partial Response     2026-03-01  More Chemotherapy
4    Partial Response     2026-02-04        Observation
..                ...            ...                ...
995            Failed     2026-01-25        Observation
996            Failed     2026-02-03  More Chemotherapy
997        Successful     2026-01-06  Radiation Therapy
998  Partial Response     2026-02-18  More Chemotherapy
999           Ongoing     2026-03-03  More Chemotherapy

[1000 rows x 6 columns]>

In [16]:
medical_xl['Outcome'].unique()

array(['Ongoing', 'Failed', 'Partial Response', 'Successful'],
      dtype=object)

In [9]:
medical_xl['Treatment Type'].unique

array(['Radiation Therapy', 'Targeted Therapy', 'Surgery',
       'Immunotherapy', 'Chemotherapy'], dtype=object)

In [12]:
need_therapy = medical_xl[medical_xl['Treatment Type'].str.lower().str.contains("therapy")]

In [17]:
need_therapy['Treatment Type'].unique

<bound method Series.unique of 0      Radiation Therapy
1      Radiation Therapy
2       Targeted Therapy
4          Immunotherapy
6      Radiation Therapy
             ...
994    Radiation Therapy
995        Immunotherapy
997     Targeted Therapy
998        Immunotherapy
999     Targeted Therapy
Name: Treatment Type, Length: 788, dtype: object>

In [23]:
need_therapy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 788 entries, 0 to 999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient ID      788 non-null    object
 1   Treatment Date  788 non-null    datetime64[ns]
 2   Treatment Type  788 non-null    object
 3   Outcome         788 non-null    object
 4   Follow-up Date  788 non-null    datetime64[ns]
 5   Next Steps      788 non-null    object
dtypes: datetime64[ns](2), object(4)
memory usage: 43.1+ KB

In [21]:
 successful_surgery= medical_xl[(medical_xl['Treatment Type']== "Surgery") & (medical_xl['Outcome'] == 'Successful')]

In [22]:
successful_surgery.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63 entries, 31 to 991
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient ID      63 non-null     object
 1   Treatment Date  63 non-null     datetime64[ns]
 2   Treatment Type  63 non-null     object
 3   Outcome         63 non-null     object
 4   Follow-up Date  63 non-null     datetime64[ns]
 5   Next Steps      63 non-null     object
dtypes: datetime64[ns](2), object(4)
memory usage: 3.4+ KB

In [24]:
medical_xl_patient = pd.read_excel('excel_files/general_patient.xlsx')
medical_xl_patient.head(4)

,Patient ID,Name,Age,Gender,Contact Number,Email,Cancer Type,Stage,Diagnosis Date,Risk Factors
0,bb6feeba-6f77-4c85-a544-a557920326d9,Zachary Duran,79,Other,+1-247-922-4552x08707,jasoncohen@example.com,Lung Cancer,Stage 3,2026-02-22,Smoking
1,b85bc8b4-175a-450a-8530-92efb05f0ddb,Justin Daniels,100,Female,(983)863-5557x8892,tarnold@example.org,Breast Cancer,Stage 1,2026-02-10,Family History
2,f520ff0b-45b1-44a7-965b-5824147bddea,Taylor Bailey,22,Male,(332)363-7899,ymunoz@example.net,Lung Cancer,Stage 4,2026-01-14,NaN
3,df8599a7-6283-4a9c-86a1-f90c05694b8e,Joseph Ballard,37,Other,(668)668-4684x6941,briggsmanuel@example.org,Lung Cancer,Stage 4,2026-01-19,Family History

In [20]:
medical_xl_patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient ID      1000 non-null   object
 1   Name            1000 non-null   object
 2   Age             1000 non-null   int64
 3   Gender          1000 non-null   object
 4   Contact Number  1000 non-null   object
 5   Email           1000 non-null   object
 6   Cancer Type     1000 non-null   object
 7   Stage           1000 non-null   object
 8   Diagnosis Date  1000 non-null   datetime64[ns]
 9   Risk Factors    755 non-null    object
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 78.3+ KB

In [26]:
medical_xl_patient.columns
successful_surgery.columns

Index(['Patient ID', 'Treatment Date', 'Treatment Type', 'Outcome',
       'Follow-up Date', 'Next Steps'],
      dtype='object')

In [ ]:
pd.merge medical_xl_patient['Patient ID', 'Name', 'Age', 'Gender','Cancer Type'] successful_surgery[['Patient ID', 'Treatment Date', 'Outcome', 'Next Steps']]

In [30]:
medical_xl_patient.head()
# successful_surgery.head()

,Patient ID,Name,Age,Gender,Contact Number,Email,Cancer Type,Stage,Diagnosis Date,Risk Factors
0,bb6feeba-6f77-4c85-a544-a557920326d9,Zachary Duran,79,Other,+1-247-922-4552x08707,jasoncohen@example.com,Lung Cancer,Stage 3,2026-02-22,Smoking
1,b85bc8b4-175a-450a-8530-92efb05f0ddb,Justin Daniels,100,Female,(983)863-5557x8892,tarnold@example.org,Breast Cancer,Stage 1,2026-02-10,Family History
2,f520ff0b-45b1-44a7-965b-5824147bddea,Taylor Bailey,22,Male,(332)363-7899,ymunoz@example.net,Lung Cancer,Stage 4,2026-01-14,NaN
3,df8599a7-6283-4a9c-86a1-f90c05694b8e,Joseph Ballard,37,Other,(668)668-4684x6941,briggsmanuel@example.org,Lung Cancer,Stage 4,2026-01-19,Family History
4,4c3ff7a1-1ea2-4229-8c47-e8de21cfaabe,Maureen Hardy,49,Male,(886)745-1209x6844,vfrancis@example.net,Pancreatic Cancer,Stage 1,2026-01-31,Obesity

In [28]:
pd.merge(left = successful_surgery, right = medical_xl_patient, how = 'left', on ='Patient ID')

,Patient ID,Treatment Date,Treatment Type,Outcome,Follow-up Date,Next Steps,Name,Age,Gender,Contact Number,Email,Cancer Type,Stage,Diagnosis Date,Risk Factors
0,30024897-6a8c-4123-9691-fa58077f3a2c,2026-01-21,Surgery,Successful,2026-01-14,Palliative Care,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,aeba3d67-1479-4993-b4e1-40fb183b9dea,2026-01-21,Surgery,Successful,2026-02-09,Observation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,c1c2a975-229c-4911-a775-bd16c07623f6,2026-02-24,Surgery,Successful,2026-01-25,Observation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,3a8b24cf-4253-4676-a085-555917a69bae,2026-01-19,Surgery,Successful,2026-02-07,Observation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,49ab687c-6a9f-41ef-980f-2359d9bb811c,2026-01-17,Surgery,Successful,2026-01-02,Radiation Therapy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,c29dbc38-1fe8-4ad1-ac79-36d2c4c3d931,2026-03-03,Surgery,Successful,2026-02-27,Observation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
59,b73daf34-f8ae-4c85-af43-951d3a862836,2026-01-02,Surgery,Successful,2026-01-12,Observation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
60,2ce0f315-57b1-4672-8c89-0de3f09c34d0,2026-03-05,Surgery,Successful,2026-01-13,More Chemotherapy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
61,95fa0ec0-c9a8-4a81-8c2d-d18018de3c31,2026-02-23,Surgery,Successful,2026-01-22,More Chemotherapy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
62,c4dfd0ad-da28-463b-be74-378f2623cc54,2026-02-21,Surgery,Successful,2026-02-13,Observation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [ ]:
 successful_surgery= medical_xl[(medical_xl['Treatment Type']== "Surgery") & (medical_xl['Outcome'] == 'Successful')]

In [22]:
def extract_xls():
    filename = input("file to extract is: ")
    excel_file =  ('./excel_files/' + filename + '.xlsx')
    file = pd.read_excel(excel_file)
    # print(file.head(3), '\n')
    # print(file.info(), '\n')
    return file

In [29]:
def transform_excel(file, treatment_type, outcome):
    treatment_outcome = file[(file['Treatment Type']== treatment_type) & (file['Outcome'] == outcome)]
    print(treatment_outcome.head())
    return treatment_outcome

In [24]:
def load_excel(file):
    names = input("whats your filename: ")
    # save = file.to_csv()
    # print(save.head())
    # csv_f = file.to_csv(names + '.csv')
    file.to_excel(names + '.xlsx')
    return f"file is saved as {names}.xlsx"

In [41]:
# make this an if/else wth csv
def load_define(file, output_file_name, output_type):
    # save = file.to_csv()
    # print(save.head())
    # csv_f = file.to_csv(output_file_name + '.csv')
    file.to_csv(output_file_name + '.' + output_type, index = False)
    # file.to_excel(output_file_name + output_type, index= False)
    return f"file is saved as {output_file_name}.{output_type}"

In [84]:
load_excel(patient)

whats your filename:  chizzy

'file is saved as chizzy.xlsx'

In [26]:
treatment = extract_xls()

file to extract is:  treatment_history

In [32]:
successful_radiation =transform_excel(treatment, 'Radiation Therapy', 'Successful')

                              Patient ID Treatment Date     Treatment Type  \
6   fe5e9dba-6e4b-451f-8f0f-e44a0108dca9     2026-01-18  Radiation Therapy
22  c369f7c4-58ae-44bf-9315-af7cf90579bf     2026-01-28  Radiation Therapy
25  39f49b54-302c-4da8-9e8e-4e00e771249a     2026-02-09  Radiation Therapy
28  abd5ea80-8bd3-42ed-a5fe-cc353ece63b1     2026-03-01  Radiation Therapy
38  0636c802-4e13-4212-8dff-b37e82b0ca08     2026-01-12  Radiation Therapy

       Outcome Follow-up Date         Next Steps
6   Successful     2026-01-16  Radiation Therapy
22  Successful     2026-03-04  Radiation Therapy
25  Successful     2026-01-23        Observation
28  Successful     2026-03-01        Observation
38  Successful     2026-01-19    Palliative Care

In [33]:
load_excel(successful_radiation)

whats your filename:  success_radiation

'file is saved as success_radiation.xlsx'

In [42]:
load_define(successful_radiation, 'radiation_four', 'csv')

'file is saved as radiation_four.csv'

In [30]:
filename = input("whats the file to extract")
# excel_file =  ('./' + filename)
excel_file =  ('./excelfiles/' + filename + '.xlsx')
print(excel_file)

whats the file to extract excel_files/general_patient.xlsx

./excel_files/general_patient.xlsx