In [1]:
import pandas as pd

In [14]:
performances = pd.read_csv('Students Performance.csv')

In [15]:
performances

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [4]:
performances.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [16]:
performances.columns.str.lower()

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [17]:
performances.columns = performances.columns.str.lower()

In [18]:
performances.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [19]:
performances.rename({'race/ethnicity': 'ethnicity'}, axis='columns', inplace=True )

In [4]:
performances.rename

NameError: name 'performance' is not defined

In [9]:
performances.columns

Index(['gender', 'ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [12]:
performances.columns = ['ethnicity', 'gender', 'parental_level_of_education', 'lunch', 'test_preparation course', 'math score', 'reading score',
       'writing score']

In [13]:
performances

,ethnicity,gender,parental_level_of_education,lunch,test_preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [22]:
performances.columns = performances.columns.str.replace(' ', '_')

In [23]:
performances.columns

Index(['gender', 'ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')

In [24]:
performances

,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [25]:
performances['gender'].unique()

array(['female', 'male'], dtype=object)

In [26]:
performances['ethnicity'].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [27]:
performances['parental_level_of_education'].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [28]:
performances.columns

Index(['gender', 'ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')

In [29]:
performances['lunch'].unique()

array(['standard', 'free/reduced'], dtype=object)

In [30]:
performances['test_preparation_course'].unique()

array(['none', 'completed'], dtype=object)

In [31]:
performances['math_score'].max()

100

In [32]:
performances['math_score'].min()

0

In [33]:
performances['reading_score'].max()

100

In [34]:
performances['reading_score'].min()

17

In [35]:
performances['writing_score'].max()

100

In [36]:
performances['writing_score'].min()

10

In [37]:
performances['math_score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [46]:
performances['total_score'] =sum([performances['math_score'], performances['reading_score'], performances['writing_score']])

In [47]:
performances

,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,average_score,total_score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,218
1,female,group C,some college,standard,completed,69,90,88,82.333333,247
2,female,group B,master's degree,standard,none,90,95,93,92.666667,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,148
4,male,group C,some college,standard,none,76,78,75,76.333333,229
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000,282
996,male,group C,high school,free/reduced,none,62,55,55,57.333333,172
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000,195
998,female,group D,some college,standard,completed,68,78,77,74.333333,223
999,female,group D,some college,free/reduced,none,77,86,86,83.000000,249

In [39]:
scores =['math_score', 'reading_score', 'writing_score']

In [42]:
del performances['tester_score']

In [44]:
performances['average_score'] = performances[scores].mean(axis=1)

In [45]:
performances

,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667
1,female,group C,some college,standard,completed,69,90,88,82.333333
2,female,group B,master's degree,standard,none,90,95,93,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333
4,male,group C,some college,standard,none,76,78,75,76.333333
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000
998,female,group D,some college,standard,completed,68,78,77,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,83.000000

In [30]:
performances.groupby(['gender'])[['math_score','reading_score', 'writing_score', 'total_score', 'average_score']].sum()

        math_score  reading_score  writing_score  total_score  average_score
gender
female       32962          37611          37538       108111   36037.000000
male         33127          31558          30516        95201   31733.666667

In [31]:
performances.groupby(['gender', 'ethnicity', 'test_preparation_course'])[['math_score','reading_score', 'writing_score',]].sum()

                                          math_score  reading_score  \
gender ethnicity test_preparation_course
female group A   completed                       813            924
                 none                           1294           1560
       group B   completed                      2192           2608
                 none                           4194           4784
       group C   completed                      4561           5334
                 none                           6605           7616
       group D   completed                      2980           3403
                 none                           5437           6149
       group E   completed                      1818           1968
                 none                           3068           3265
male   group A   completed                      1303           1278
                 none                           2075           1994
       group B   completed                      2377           2346
                 none                           3293           3059
       group C   completed                      3336           3284
                 none                           6062           5810
       group D   completed                      2743           2677
                 none                           6489           6119
       group E   completed                      2828           2632
                 none                           2621           2359

                                          writing_score
gender ethnicity test_preparation_course
female group A   completed                          919
                 none                              1524
       group B   completed                         2607
                 none                              4678
       group C   completed                         5440
                 none                              7480
       group D   completed                         3540
                 none                              6138
       group E   completed                         1992
                 none                              3220
male   group A   completed                         1279
                 none                              1856
       group B   completed                         2281
                 none                              2898
       group C   completed                         3271
                 none                              5446
       group D   completed                         2746
                 none                              5954
       group E   completed                         2567
                 none                              2218

In [32]:
# def extract_data():
#     perms = pd.read_csv('Students Performance.csv')
#     perms
#     return True

In [33]:
# def transform_perms():
#     extract_data()
#     perms = perms.columns.str.replace(' ', '_').lower()
#     return perms

In [34]:
def gender_based_score():
    perms = pd.read_csv('Students Performance.csv')
    perms.columns = perms.columns.str.replace(' ', '_')
    perms.columns = perms.columns.str.lower()
    perms.rename({'race/ethnicity': 'ethnicity'}, axis='columns', inplace=True )
    scores =['math_score', 'reading_score', 'writing_score']
    perms['total_score'] = perms[scores].sum(axis=1)
    perms['average_score'] = perms[scores].mean(axis=1)
    scores1 = ['math_score','reading_score', 'writing_score', 'total_score', 'average_score']
    scores_by_gender = perms.groupby(['gender'])[scores1].sum()
    scores_by_gender.to_csv('scores_by_gender')
    
    return True

In [39]:
gender_based_score()

True

In [61]:
def ade(a,s):
    d = a+s
    return d

In [62]:
def av(d):
    f = d/2
    return f

In [71]:
ade(2,3)

5

In [72]:
av(ade(2,4))

3.0

In [50]:
def extract_data(file_name):
    df = pd.read_csv(file_name)
    return df

In [62]:
file_one = extract_data("Students Performance.csv")

In [63]:
file_one

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [60]:
def transform_data(df):
    df.columns = df.columns.str.replace(' ', '_')
    df.columns = df.columns.str.lower()
    df.rename({'race/ethnicity': 'ethnicity'}, axis='columns', inplace=True )
    return df

In [64]:
file_two = transform_data(file_one)

In [53]:
transform_data(extract_data('Students Performance.csv'))

,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [54]:
def feature_eng(df):
    scores =['math_score', 'reading_score', 'writing_score']
    df['total_score'] = df[scores].sum(axis=1)
    df['average_score'] = df[scores].mean(axis=1)
    return df

In [55]:
feature_eng(transform_data(extract_data('Students Performance.csv')))

,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,172,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,195,65.000000
998,female,group D,some college,standard,completed,68,78,77,223,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,249,83.000000

In [56]:
def scores_by_gender(df):
    aggreate_scores = ['math_score','reading_score', 'writing_score', 'total_score', 'average_score']
    scores_by_gender = df.groupby(['gender'])[aggreate_scores].sum()
    scores_by_gender_report = scores_by_gender.to_csv('scores_by_gender_report')
    return True

In [57]:
scores_by_gender(feature_eng(transform_data(extract_data('Students Performance.csv'))))

True

In [ ]:
df['gender']= female

In [65]:
def extract_data(file_name):
    df = pd.read_csv(file_name)
    return df

In [66]:
def transform_data(df):
    df.columns = df.columns.str.replace(' ', '_')
    df.columns = df.columns.str.lower()
    df.rename({'race/ethnicity': 'ethnicity'}, axis='columns', inplace=True )
    return df

In [74]:
def feature_eng(df):
    scores =['math_score', 'reading_score', 'writing_score']
    df['total_score'] = df[scores].sum(axis=1)
    df['average_score'] = df[scores].mean(axis=1)
    return df

In [72]:
def scores_by_gender(df):
    aggreate_scores = ['math_score','reading_score', 'writing_score', 'total_score', 'average_score']
    scores_by_gender = df.groupby(['gender'])[aggreate_scores].sum()
    scores_by_gender_report = scores_by_gender.to_csv('scores_by_gender_report_one')
    return True

In [68]:
extract_data("Students Performance.csv")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [82]:
file_one = extract_data("Students Performance.csv")

In [83]:
file_two = transform_data(file_one)

In [84]:
file_three = feature_eng(file_two)

In [85]:
file_four = scores_by_gender(file_three)